# Generated by Django 4.2.4 on 2023-08-08 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Runner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("runnerToken", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(max_length=255, null=True)),
                ("lastContact", models.DateTimeField()),
                ("ip", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RunnerRegistrationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registrationToken", models.CharField(max_length=255, unique=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RunnerJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField()),
                ("type", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                ("privatePayload", models.JSONField()),
                ("state", models.CharField(max_length=255)),
                ("failures", models.IntegerField(default=0)),
                ("error", models.CharField(max_length=255, null=True)),
                ("priority", models.IntegerField()),
                ("processingJobToken", models.CharField(max_length=255, null=True)),
                ("progress", models.FloatField(null=True)),
                ("startedAt", models.DateTimeField(null=True)),
                ("finishedAt", models.DateTimeField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "dependsOnRunnerJob",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transcoding.runnerjob",
                    ),
                ),
                (
                    "runner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transcoding.runner",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="runner",
            name="runnerRegistrationToken",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transcoding.runnerregistrationtoken",
            ),
        ),
    ]
