# Generated by Django 4.2.4 on 2023-08-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcoding", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runnerjob",
            name="dependsOnRunnerJob",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transcoding.runnerjob",
            ),
        ),
        migrations.AlterField(
            model_name="runnerjob",
            name="error",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="runnerjob",
            name="finishedAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="runnerjob",
            name="processingJobToken",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="runnerjob",
            name="progress",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="runnerjob",
            name="runner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transcoding.runner",
            ),
        ),
        migrations.AlterField(
            model_name="runnerjob",
            name="startedAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="runnerjob",
            name="state",
            field=models.IntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Processing"),
                    (3, "Completed"),
                    (4, "Errored"),
                    (5, "Waiting for parent job"),
                    (6, "Cancelled"),
                    (7, "Parent errored"),
                    (8, "Parent cancelled"),
                    (9, "Completing"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="runnerjob",
            name="type",
            field=models.CharField(
                choices=[
                    ("vod-web-video-transcoding", "Vod Web Video Transcoding"),
                    ("vod-hls-transcoding", "Vod Hls Transcoding"),
                    ("vod-audio-merge-transcoding", "Vod Audio Merge Transcoding"),
                    ("live-rtmp-hls-transcoding", "Live Rtmp Hls Transcoding"),
                    ("video-studio-transcoding", "Video Studio Transcoding"),
                ],
                max_length=255,
            ),
        ),
    ]
