# Generated by Django 4.2.4 on 2023-08-16 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcoding", "0002_alter_runnerjob_dependsonrunnerjob_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField()),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (1, "Published"),
                            (2, "To transcode"),
                            (3, "To import"),
                            (4, "Waiting for live"),
                            (5, "Live ended"),
                            (6, "To move to external storage"),
                            (7, "Transcoding failed"),
                            (8, "To move to external storage failed"),
                            (9, "To edit"),
                        ]
                    ),
                ),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="VideoJobInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("pendingMove", models.IntegerField(default=0)),
                ("pendingTranscode", models.IntegerField(default=0)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobInfo",
                        to="transcoding.video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resolution",
                    models.IntegerField(
                        choices=[
                            (0, "H Novideo"),
                            (144, "H 144P"),
                            (240, "H 240P"),
                            (360, "H 360P"),
                            (480, "H 480P"),
                            (720, "H 720P"),
                            (1080, "H 1080P"),
                            (1440, "H 1440P"),
                            (2160, "H 4K"),
                        ]
                    ),
                ),
                ("size", models.BigIntegerField()),
                ("extname", models.CharField(max_length=255)),
                ("infoHash", models.CharField(blank=True, max_length=255, null=True)),
                ("fps", models.IntegerField(default=-1)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "metadataUrl",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fileUrl", models.CharField(blank=True, max_length=255, null=True)),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
                ("torrentUrl", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "torrentFilename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "storage",
                    models.CharField(
                        choices=[
                            ("FILE_SYSTEM", "File System"),
                            ("OBJECT_STORAGE", "Object Storage"),
                        ],
                        default="FILE_SYSTEM",
                        max_length=255,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="transcoding.video",
                    ),
                ),
            ],
            options={
                "db_table": "video_files",
                "indexes": [
                    models.Index(
                        fields=["video"], name="video_files_video_i_f1bcce_idx"
                    )
                ],
            },
        ),
    ]
