# Generated by Django 2.0 on 2018-08-08 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="ltipassportscope", name="consumer_site"),
        migrations.RemoveField(model_name="ltipassportscope", name="lti_passport"),
        migrations.RemoveField(model_name="ltipassportscope", name="playlist"),
        migrations.AddField(
            model_name="ltipassport",
            name="consumer_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lti_passport_scopes",
                to="core.ConsumerSite",
            ),
        ),
        migrations.AddField(
            model_name="ltipassport",
            name="playlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lti_passport_scopes",
                to="core.Playlist",
            ),
        ),
        migrations.AlterField(
            model_name="ltipassport",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lti_passports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ltipassport",
            name="is_enabled",
            field=models.BooleanField(
                default=True,
                help_text="whether the passport is enabled",
                verbose_name="is enabled",
            ),
        ),
        migrations.AlterField(
            model_name="ltipassport",
            name="oauth_consumer_key",
            field=models.CharField(
                editable=False,
                help_text="oauth consumer key to authenticate an LTI consumer on the LTI provider",
                max_length=255,
                unique=True,
                verbose_name="oauth consumer key",
            ),
        ),
        migrations.AlterField(
            model_name="ltipassport",
            name="shared_secret",
            field=models.CharField(
                editable=False,
                help_text="LTI Shared secret",
                max_length=255,
                verbose_name="shared secret",
            ),
        ),
        migrations.DeleteModel(name="LTIPassportScope"),
    ]
