# Generated by Django 2.0.5 on 2018-05-14 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import psqlextra.indexes.conditional_unique_index

import marsha.core.managers


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial_models")]

    operations = [
        migrations.AlterModelManagers(
            name="user", managers=[("objects", marsha.core.managers.UserManager())]
        ),
        migrations.AddField(
            model_name="audiotrack",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="authoring",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="consumersite",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="organizationmanager",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="playlistaccess",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="playlistvideo",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="signtrack",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="siteadmin",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="siteorganization",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="subtitletrack",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="consumersite",
            name="name",
            field=models.CharField(
                help_text="Name of the site", max_length=255, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(
                help_text="name of the organization",
                max_length=255,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_playlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to="core.Organization",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="author",
            field=models.ForeignKey(
                help_text="author of the video",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_videos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AlterUniqueTogether(name="audiotrack", unique_together=set()),
        migrations.AlterUniqueTogether(name="authoring", unique_together=set()),
        migrations.AlterUniqueTogether(
            name="organizationmanager", unique_together=set()
        ),
        migrations.AlterUniqueTogether(name="playlistaccess", unique_together=set()),
        migrations.AlterUniqueTogether(name="playlistvideo", unique_together=set()),
        migrations.AlterUniqueTogether(name="signtrack", unique_together=set()),
        migrations.AlterUniqueTogether(name="siteadmin", unique_together=set()),
        migrations.AlterUniqueTogether(name="siteorganization", unique_together=set()),
        migrations.AlterUniqueTogether(name="subtitletrack", unique_together=set()),
        migrations.AddIndex(
            model_name="audiotrack",
            index=psqlextra.indexes.conditional_unique_index.ConditionalUniqueIndex(
                condition='"deleted" IS NULL',
                fields=["video", "language"],
                name="audio_track_video_i_fe6276_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="authoring",
            index=psqlextra.indexes.conditional_unique_index.ConditionalUniqueIndex(
                condition='"deleted" IS NULL',
                fields=["user", "organization"],
                name="authoring_user_id_0ce1c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmanager",
            index=psqlextra.indexes.conditional_unique_index.ConditionalUniqueIndex(
                condition='"deleted" IS NULL',
                fields=["user", "organization"],
                name="organizatio_user_id_a56b6d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="playlistaccess",
            index=psqlextra.indexes.conditional_unique_index.ConditionalUniqueIndex(
                condition='"deleted" IS NULL',
                fields=["user", "playlist"],
                name="playlist_ac_user_id_c7df1b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="playlistvideo",
            index=psqlextra.indexes.conditional_unique_index.ConditionalUniqueIndex(
                condition='"deleted" IS NULL',
                fields=["video", "playlist"],
                name="playlist_vi_video_i_6460b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="signtrack",
            index=psqlextra.indexes.conditional_unique_index.ConditionalUniqueIndex(
                condition='"deleted" IS NULL',
                fields=["video", "language"],
                name="sign_track_video_i_8ae92b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="siteadmin",
            index=psqlextra.indexes.conditional_unique_index.ConditionalUniqueIndex(
                condition='"deleted" IS NULL',
                fields=["user", "site"],
                name="site_admin_user_id_62a0e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="siteorganization",
            index=psqlextra.indexes.conditional_unique_index.ConditionalUniqueIndex(
                condition='"deleted" IS NULL',
                fields=["site", "organization"],
                name="site_organi_site_id_f51dca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subtitletrack",
            index=psqlextra.indexes.conditional_unique_index.ConditionalUniqueIndex(
                condition='"deleted" IS NULL',
                fields=["video", "language", "has_closed_captioning"],
                name="subtitle_tr_video_i_7ef2a4_idx",
            ),
        ),
    ]
