# Generated by Django 2.0 on 2018-09-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0002_video_uploaded_on")]

    operations = [
        migrations.AddField(
            model_name="video",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("error", "error"),
                    ("ready", "ready"),
                ],
                default="pending",
                help_text="state of the upload and transcoding pipeline in AWS.",
                max_length=20,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="uploaded_on",
            field=models.DateTimeField(
                blank=True,
                help_text="datetime at which the active version of the video was uploaded.",
                null=True,
                verbose_name="uploaded on",
            ),
        ),
    ]
