# Generated by Django 2.0.5 on 2018-05-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0002_soft_deletion")]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="name",
            field=models.CharField(
                default="Playlist",
                help_text="name of the playlist",
                max_length=255,
                verbose_name="name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="description of the video",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="name",
            field=models.CharField(
                default="Video",
                help_text="name of the video",
                max_length=255,
                verbose_name="name",
            ),
            preserve_default=False,
        ),
    ]
