# Generated by Django 2.0.5 on 2018-05-23 11:26

from django.db import migrations

import marsha.core.base_models


class Migration(migrations.Migration):

    dependencies = [("core", "0004_duplicated_from__blank")]

    operations = [
        migrations.RemoveIndex(
            model_name="audiotrack", name="audio_track_video_i_fe6276_idx"
        ),
        migrations.RemoveIndex(
            model_name="authoring", name="authoring_user_id_0ce1c4_idx"
        ),
        migrations.RemoveIndex(
            model_name="organizationmanager", name="organizatio_user_id_a56b6d_idx"
        ),
        migrations.RemoveIndex(
            model_name="playlistaccess", name="playlist_ac_user_id_c7df1b_idx"
        ),
        migrations.RemoveIndex(
            model_name="playlistvideo", name="playlist_vi_video_i_6460b7_idx"
        ),
        migrations.RemoveIndex(
            model_name="signtrack", name="sign_track_video_i_8ae92b_idx"
        ),
        migrations.RemoveIndex(
            model_name="siteadmin", name="site_admin_user_id_62a0e6_idx"
        ),
        migrations.RemoveIndex(
            model_name="siteorganization", name="site_organi_site_id_f51dca_idx"
        ),
        migrations.RemoveIndex(
            model_name="subtitletrack", name="subtitle_tr_video_i_7ef2a4_idx"
        ),
        migrations.AddIndex(
            model_name="audiotrack",
            index=marsha.core.base_models.NonDeletedUniqueIndex(
                fields=["video", "language"], name="audio_track_video_i_fe6276_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authoring",
            index=marsha.core.base_models.NonDeletedUniqueIndex(
                fields=["user", "organization"], name="authoring_user_id_0ce1c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmanager",
            index=marsha.core.base_models.NonDeletedUniqueIndex(
                fields=["user", "organization"], name="organizatio_user_id_a56b6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlistaccess",
            index=marsha.core.base_models.NonDeletedUniqueIndex(
                fields=["user", "playlist"], name="playlist_ac_user_id_c7df1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlistvideo",
            index=marsha.core.base_models.NonDeletedUniqueIndex(
                fields=["video", "playlist"], name="playlist_vi_video_i_6460b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signtrack",
            index=marsha.core.base_models.NonDeletedUniqueIndex(
                fields=["video", "language"], name="sign_track_video_i_8ae92b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="siteadmin",
            index=marsha.core.base_models.NonDeletedUniqueIndex(
                fields=["user", "site"], name="site_admin_user_id_62a0e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="siteorganization",
            index=marsha.core.base_models.NonDeletedUniqueIndex(
                fields=["site", "organization"], name="site_organi_site_id_f51dca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subtitletrack",
            index=marsha.core.base_models.NonDeletedUniqueIndex(
                fields=["video", "language", "has_closed_captioning"],
                name="subtitle_tr_video_i_7ef2a4_idx",
            ),
        ),
    ]
