version: "3"

services:
  db:
    image: postgres:10.3
    env_file: env.d/ci

  app:
    image: "marsha:${CIRCLE_SHA1}${IMAGE_SUFFIX}-dev"
    env_file: env.d/ci
    volumes:
      - ./dist:/app/dist
    depends_on:
      - "db"

  crowdin:
    image: fundocker/crowdin:2.0.27
    volumes:
      - ".:/app"
    environment:
      - CROWDIN_API_KEY
      - CROWDIN_PROJECT_ID
      - CROWDIN_BASE_PATH
    working_dir: /app
