# Generated by Django 4.0.7 on 2022-09-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_alter_audiotrack_deleted_and_more"),
        ("deposit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filedepository",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="description of the file depository",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="filedepository",
            name="playlist",
            field=models.ForeignKey(
                help_text="playlist to which this file depository belongs",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="core.playlist",
                verbose_name="playlist",
            ),
        ),
        migrations.AlterField(
            model_name="filedepository",
            name="position",
            field=models.PositiveIntegerField(
                default=0,
                help_text="position of this file depository in the playlist",
                verbose_name="position",
            ),
        ),
        migrations.AlterField(
            model_name="filedepository",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="title of the file depository",
                max_length=255,
                null=True,
                verbose_name="title",
            ),
        ),
    ]
