# Generated by Django 4.1.7 on 2023-04-06 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deposit", "0004_alter_filedepository_playlist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="depositedfile",
            options={
                "ordering": ["-uploaded_on", "-created_on"],
                "verbose_name": "Deposited file",
                "verbose_name_plural": "Deposited files",
            },
        ),
    ]
