# Generated by Django 5.0.9 on 2025-04-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposit", "0005_alter_depositedfile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositedfile",
            name="storage_location",
            field=models.CharField(
                choices=[("AWS", "AWS"), ("SCW", "SCW")],
                default="SCW",
                help_text="Location used to store the deposited file",
                max_length=255,
                verbose_name="storage location",
            ),
        ),
    ]
