# Generated by Django 4.1.9 on 2023-06-13 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("deposit", "0005_alter_depositedfile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="filedepository",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                help_text="owner of the file depository",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
            preserve_default=False,
        ),
    ]
