# Generated by Django 5.0.9 on 2025-06-11 17:27

from django.db import migrations


def set_storage_location_to_aws(apps, schema_editor):
    """Update the storage_location field for existing deposited files."""
    DepositedFile = apps.get_model("deposit", "DepositedFile")
    DepositedFile.objects.all().update(storage_location="AWS_S3")


class Migration(migrations.Migration):
    dependencies = [
        ("deposit", "0006_depositedfile_storage_location"),
    ]

    operations = [
        migrations.RunPython(set_storage_location_to_aws, migrations.RunPython.noop),
    ]
