# Generated by Django 5.0.9 on 2025-07-14 13:31

from django.db import migrations

from marsha.core.defaults import AWS_S3


def fix_storage_location_to_aws(apps, schema_editor):
    """Fix the storage_location field for existing deposited files on AWS."""
    DepositedFile = apps.get_model("deposit", "DepositedFile")
    DepositedFile.objects.filter(storage_location="AWS_S3").update(
        storage_location=AWS_S3
    )


class Migration(migrations.Migration):
    dependencies = [
        ("deposit", "0007_depositedfile_fill_storage_location"),
    ]

    operations = [
        migrations.RunPython(fix_storage_location_to_aws, migrations.RunPython.noop),
    ]
