"""Tests for the TimedTextTrack transcript-callback API of the Marsha project."""
from django.core.files.storage import storages
from django.test import TestCase, override_settings

import responses

from marsha.core.factories import TimedTextTrackFactory


# @override_settings(
#     AWS_ACCESS_KEY_ID="test",
#     AWS_SECRET_ACCESS_KEY="test",
#     AWS_S3_REGION_NAME="us-east-1",
#     AWS_BASE_NAME="test",
#     AWS_SOURCE_BUCKET_NAME="test-source-bucket",
# )
class TimedTextTrackTranscriptCallbackAPITest(TestCase):
    """Test the transcript-callback API of the timed text track object."""

    maxDiff = None

    def test_api_timed_text_track_transcript_options(self):
        """Anonymous users should be allowed to options to the transcript-callback API."""
        timed_text_track = TimedTextTrackFactory()

        response = self.client.options(
            f"/api/videos/{timed_text_track.video.pk}/timedtexttracks/"
            f"{timed_text_track.id}/transcript-callback/"
        )

        self.assertEqual(response.status_code, 200)

    @responses.activate
    def test_api_timed_text_track_transcript_post(self):
        """Anonymous users should be allowed to post to the transcript-callback API."""
        timed_text_track = TimedTextTrackFactory(video__title="Test video")

        data = {
            "request_id": "G-55b3c720",
            "payload": {
                "prediction": "1\n00:00:09,470 --> 00:00:13,680\nCreative Commons est une organisation non gouvernementale à but non lucratif.\n\n2\n00:00:15,780 --> 00:00:19,400\nElle a conçu des licences qui ont été adaptées dans plus de 70 pays,\n\n3\n00:00:19,520 --> 00:00:20,240\ndont la France.\n\n4\n00:00:22,740 --> 00:00:24,930\nUtilisées par les créateurs et leurs partenaires,\n\n5\n00:00:25,510 --> 00:00:31,230\nces licences permettent de réutiliser des contenus et des données de manière simple et sécurisée.\n\n6\n00:00:34,910 --> 00:00:39,150\nLes six licences jouent sur différentes options qui peuvent être combinées les unes aux autres.\n\n7\n00:00:39,590 --> 00:00:43,350\nElles conditionnent le degré de liberté que l'auteur accorde aux utilisateurs.\n\n8\n00:00:44,250 --> 00:00:46,870\nDes outils protègent et valorisent le domaine public.\n\n9\n00:00:51,440 --> 00:00:52,300\nLa mention baille,\n\n10\n00:00:52,580 --> 00:00:54,220\nqui impose la citation de l'auteur,\n\n11\n00:00:54,480 --> 00:00:55,320\nest obligatoire.\n\n12\n00:00:58,990 --> 00:01:04,960\nL'option SA indique que l'œuvre doit être partagée sous la même licence que celle choisie par l'auteur originaire.\n\n13\n00:01:07,180 --> 00:01:11,380\nL'option ND signifie que l'utilisateur n'a pas le droit de modifier l'œuvre.\n\n14\n00:01:15,100 --> 00:01:17,750\nL'option NC interdit tout usage commercial.\n\n15\n00:01:21,540 --> 00:01:24,320\nCes licences sont interopérables et non exclusives.\n\n16\n00:01:26,420 --> 00:01:27,920\nElles évitent des coûts de transaction,\n\n17\n00:01:28,520 --> 00:01:34,600\nfluidifient les usages numériques et s'inscrivent comme un complément aux droits d'auteur.\n\n18\n00:01:36,000 --> 00:01:40,120\nLes licences Creative Commons sont compatibles avec le système juridique français.\n\n19\n00:01:42,550 --> 00:01:46,550\nElles créent un équilibre entre les droits des créateurs et ceux des utilisateurs.\n\n20\n00:01:50,910 --> 00:01:51,290\nAujourd'hui,\n\n21\n00:01:51,890 --> 00:01:56,760\nil est possible d'accéder à des millions de contenus et de données sous licence Creative Commons.\n",
                "prediction_raw": {
                    "transcription": [
                        {
                            "words": [
                                {
                                    "word": "Creative",
                                    "time_begin": 9.476939999999999,
                                    "time_end": 9.89733,
                                    "confidence": 0.75,
                                },
                                {
                                    "word": " Commons",
                                    "time_begin": 9.93737,
                                    "time_end": 10.35775,
                                    "confidence": 0.82,
                                },
                                {
                                    "word": " est",
                                    "time_begin": 10.517900000000001,
                                    "time_end": 10.638010000000001,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " une",
                                    "time_begin": 10.678049999999999,
                                    "time_end": 10.79816,
                                    "confidence": 1,
                                },
                                {
                                    "word": " organisation",
                                    "time_begin": 10.8382,
                                    "time_end": 11.47878,
                                    "confidence": 1,
                                },
                                {
                                    "word": " non",
                                    "time_begin": 11.55886,
                                    "time_end": 11.67897,
                                    "confidence": 1,
                                },
                                {
                                    "word": " gouvernementale",
                                    "time_begin": 11.719000000000001,
                                    "time_end": 12.519739999999999,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " à",
                                    "time_begin": 12.67989,
                                    "time_end": 12.8,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " but",
                                    "time_begin": 12.82002,
                                    "time_end": 12.960149999999999,
                                    "confidence": 0.98,
                                },
                                {
                                    "word": " non",
                                    "time_begin": 13.020199999999999,
                                    "time_end": 13.14031,
                                    "confidence": 0.94,
                                },
                                {
                                    "word": " lucratif.",
                                    "time_begin": 13.16033,
                                    "time_end": 13.680810000000001,
                                    "confidence": 1,
                                },
                            ],
                            "language": "fr",
                            "transcription": "Creative Commons est une organisation non gouvernementale à but non lucratif.",
                            "confidence": 0.7600000000000001,
                            "time_begin": 9.476939999999999,
                            "time_end": 13.680810000000001,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " Elle",
                                    "time_begin": 15.78274,
                                    "time_end": 15.90285,
                                    "confidence": 0.97,
                                },
                                {
                                    "word": " a",
                                    "time_begin": 15.90285,
                                    "time_end": 15.98292,
                                    "confidence": 0.97,
                                },
                                {
                                    "word": " conçu",
                                    "time_begin": 16.02296,
                                    "time_end": 16.2832,
                                    "confidence": 1,
                                },
                                {
                                    "word": " des",
                                    "time_begin": 16.32324,
                                    "time_end": 16.44335,
                                    "confidence": 1,
                                },
                                {
                                    "word": " licences",
                                    "time_begin": 16.46337,
                                    "time_end": 17.00386,
                                    "confidence": 0.96,
                                },
                                {
                                    "word": " qui",
                                    "time_begin": 17.12397,
                                    "time_end": 17.24408,
                                    "confidence": 1,
                                },
                                {
                                    "word": " ont",
                                    "time_begin": 17.30414,
                                    "time_end": 17.42425,
                                    "confidence": 0.91,
                                },
                                {
                                    "word": " été",
                                    "time_begin": 17.4843,
                                    "time_end": 17.62443,
                                    "confidence": 1,
                                },
                                {
                                    "word": " adaptées",
                                    "time_begin": 17.70451,
                                    "time_end": 18.104870000000002,
                                    "confidence": 0.88,
                                },
                                {
                                    "word": " dans",
                                    "time_begin": 18.104870000000002,
                                    "time_end": 18.22498,
                                    "confidence": 0.97,
                                },
                                {
                                    "word": " plus",
                                    "time_begin": 18.245,
                                    "time_end": 18.38513,
                                    "confidence": 1,
                                },
                                {
                                    "word": " de",
                                    "time_begin": 18.38513,
                                    "time_end": 18.50524,
                                    "confidence": 1,
                                },
                                {
                                    "word": " 70",
                                    "time_begin": 18.5653,
                                    "time_end": 19.08578,
                                    "confidence": 0.05,
                                },
                                {
                                    "word": " pays,",
                                    "time_begin": 19.14583,
                                    "time_end": 19.40607,
                                    "confidence": 0.96,
                                },
                            ],
                            "language": "fr",
                            "transcription": "Elle a conçu des licences qui ont été adaptées dans plus de 70 pays,",
                            "confidence": 0.7600000000000001,
                            "time_begin": 15.78274,
                            "time_end": 19.40607,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " dont",
                                    "time_begin": 19.52618,
                                    "time_end": 19.64629,
                                    "confidence": 0.89,
                                },
                                {
                                    "word": " la",
                                    "time_begin": 19.66631,
                                    "time_end": 19.78642,
                                    "confidence": 1,
                                },
                                {
                                    "word": " France.",
                                    "time_begin": 19.80644,
                                    "time_end": 20.24684,
                                    "confidence": 0.96,
                                },
                            ],
                            "language": "fr",
                            "transcription": "dont la France.",
                            "confidence": 0.7600000000000001,
                            "time_begin": 19.52618,
                            "time_end": 20.24684,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " Utilisées",
                                    "time_begin": 22.74914,
                                    "time_end": 23.229580000000002,
                                    "confidence": 0.93,
                                },
                                {
                                    "word": " par",
                                    "time_begin": 23.229580000000002,
                                    "time_end": 23.349690000000002,
                                    "confidence": 1,
                                },
                                {
                                    "word": " les",
                                    "time_begin": 23.38973,
                                    "time_end": 23.50984,
                                    "confidence": 1,
                                },
                                {
                                    "word": " créateurs",
                                    "time_begin": 23.52986,
                                    "time_end": 24.03032,
                                    "confidence": 0.95,
                                },
                                {
                                    "word": " et",
                                    "time_begin": 24.03032,
                                    "time_end": 24.110390000000002,
                                    "confidence": 0.98,
                                },
                                {
                                    "word": " leurs",
                                    "time_begin": 24.13041,
                                    "time_end": 24.25052,
                                    "confidence": 0.89,
                                },
                                {
                                    "word": " partenaires,",
                                    "time_begin": 24.29056,
                                    "time_end": 24.931150000000002,
                                    "confidence": 0.98,
                                },
                            ],
                            "language": "fr",
                            "transcription": "Utilisées par les créateurs et leurs partenaires,",
                            "confidence": 0.7600000000000001,
                            "time_begin": 22.74914,
                            "time_end": 24.931150000000002,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " ces",
                                    "time_begin": 25.511680000000002,
                                    "time_end": 25.631790000000002,
                                    "confidence": 0.95,
                                },
                                {
                                    "word": " licences",
                                    "time_begin": 25.65181,
                                    "time_end": 26.05218,
                                    "confidence": 0.94,
                                },
                                {
                                    "word": " permettent",
                                    "time_begin": 26.072200000000002,
                                    "time_end": 26.452550000000002,
                                    "confidence": 0.94,
                                },
                                {
                                    "word": " de",
                                    "time_begin": 26.452550000000002,
                                    "time_end": 26.55264,
                                    "confidence": 1,
                                },
                                {
                                    "word": " réutiliser",
                                    "time_begin": 26.572660000000003,
                                    "time_end": 27.25328,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " des",
                                    "time_begin": 27.45347,
                                    "time_end": 27.57358,
                                    "confidence": 1,
                                },
                                {
                                    "word": " contenus",
                                    "time_begin": 27.61361,
                                    "time_end": 28.05402,
                                    "confidence": 0.98,
                                },
                                {
                                    "word": " et",
                                    "time_begin": 28.19415,
                                    "time_end": 28.31426,
                                    "confidence": 0.95,
                                },
                                {
                                    "word": " des",
                                    "time_begin": 28.294240000000002,
                                    "time_end": 28.414350000000002,
                                    "confidence": 0.93,
                                },
                                {
                                    "word": " données",
                                    "time_begin": 28.43437,
                                    "time_end": 28.77468,
                                    "confidence": 0.93,
                                },
                                {
                                    "word": " de",
                                    "time_begin": 29.79562,
                                    "time_end": 29.91573,
                                    "confidence": 1,
                                },
                                {
                                    "word": " manière",
                                    "time_begin": 29.935750000000002,
                                    "time_end": 30.23602,
                                    "confidence": 0.98,
                                },
                                {
                                    "word": " simple",
                                    "time_begin": 30.316100000000002,
                                    "time_end": 30.576340000000002,
                                    "confidence": 0.98,
                                },
                                {
                                    "word": " et",
                                    "time_begin": 30.576340000000002,
                                    "time_end": 30.67643,
                                    "confidence": 0.97,
                                },
                                {
                                    "word": " sécurisée.",
                                    "time_begin": 30.67643,
                                    "time_end": 31.23694,
                                    "confidence": 0.92,
                                },
                            ],
                            "time_begin": 25.511680000000002,
                            "time_end": 31.23694,
                            "language": "fr",
                            "transcription": "ces licences permettent de réutiliser des contenus et des données de manière simple et sécurisée.",
                            "confidence": 0.7600000000000001,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " Les",
                                    "time_begin": 34.91004,
                                    "time_end": 35.03013,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " six",
                                    "time_begin": 35.05014,
                                    "time_end": 35.19024,
                                    "confidence": 0.57,
                                },
                                {
                                    "word": " licences",
                                    "time_begin": 35.19024,
                                    "time_end": 35.67057,
                                    "confidence": 0.93,
                                },
                                {
                                    "word": " jouent",
                                    "time_begin": 35.93075,
                                    "time_end": 36.11088,
                                    "confidence": 0.74,
                                },
                                {
                                    "word": " sur",
                                    "time_begin": 36.11088,
                                    "time_end": 36.23096,
                                    "confidence": 0.91,
                                },
                                {
                                    "word": " différentes",
                                    "time_begin": 36.270990000000005,
                                    "time_end": 36.77133,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " options",
                                    "time_begin": 36.83138,
                                    "time_end": 37.19163,
                                    "confidence": 1,
                                },
                                {
                                    "word": " qui",
                                    "time_begin": 37.2917,
                                    "time_end": 37.41178,
                                    "confidence": 1,
                                },
                                {
                                    "word": " peuvent",
                                    "time_begin": 37.45181,
                                    "time_end": 37.67196,
                                    "confidence": 1,
                                },
                                {
                                    "word": " être",
                                    "time_begin": 37.71199,
                                    "time_end": 37.8721,
                                    "confidence": 1,
                                },
                                {
                                    "word": " combinées",
                                    "time_begin": 37.97217,
                                    "time_end": 38.37245,
                                    "confidence": 0.86,
                                },
                                {
                                    "word": " les",
                                    "time_begin": 38.39246,
                                    "time_end": 38.532560000000004,
                                    "confidence": 1,
                                },
                                {
                                    "word": " unes",
                                    "time_begin": 38.57259,
                                    "time_end": 38.71268,
                                    "confidence": 0.91,
                                },
                                {
                                    "word": " aux",
                                    "time_begin": 38.71268,
                                    "time_end": 38.832770000000004,
                                    "confidence": 1,
                                },
                                {
                                    "word": " autres.",
                                    "time_begin": 38.892810000000004,
                                    "time_end": 39.15299,
                                    "confidence": 0.94,
                                },
                            ],
                            "language": "fr",
                            "transcription": "Les six licences jouent sur différentes options qui peuvent être combinées les unes aux autres.",
                            "confidence": 0.72,
                            "time_begin": 34.91004,
                            "time_end": 39.15299,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " Elles",
                                    "time_begin": 39.59329,
                                    "time_end": 39.73339,
                                    "confidence": 0.98,
                                },
                                {
                                    "word": " conditionnent",
                                    "time_begin": 39.75341,
                                    "time_end": 40.29378,
                                    "confidence": 0.92,
                                },
                                {
                                    "word": " le",
                                    "time_begin": 40.313790000000004,
                                    "time_end": 40.39385,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " degré",
                                    "time_begin": 40.41386,
                                    "time_end": 40.69406,
                                    "confidence": 0.98,
                                },
                                {
                                    "word": " de",
                                    "time_begin": 40.71407,
                                    "time_end": 40.834160000000004,
                                    "confidence": 1,
                                },
                                {
                                    "word": " liberté",
                                    "time_begin": 40.85417,
                                    "time_end": 41.31449,
                                    "confidence": 0.98,
                                },
                                {
                                    "word": " que",
                                    "time_begin": 41.65473,
                                    "time_end": 41.77481,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " l'auteur",
                                    "time_begin": 41.79482,
                                    "time_end": 42.07502,
                                    "confidence": 0.92,
                                },
                                {
                                    "word": " accorde",
                                    "time_begin": 42.15507,
                                    "time_end": 42.475300000000004,
                                    "confidence": 0.98,
                                },
                                {
                                    "word": " aux",
                                    "time_begin": 42.49531,
                                    "time_end": 42.615390000000005,
                                    "confidence": 0.97,
                                },
                                {
                                    "word": " utilisateurs.",
                                    "time_begin": 42.65542,
                                    "time_end": 43.35591,
                                    "confidence": 0.97,
                                },
                            ],
                            "language": "fr",
                            "transcription": "Elles conditionnent le degré de liberté que l'auteur accorde aux utilisateurs.",
                            "confidence": 0.72,
                            "time_begin": 39.59329,
                            "time_end": 43.35591,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " Des",
                                    "time_begin": 44.25653,
                                    "time_end": 44.39663,
                                    "confidence": 1,
                                },
                                {
                                    "word": " outils",
                                    "time_begin": 44.43666,
                                    "time_end": 44.67683,
                                    "confidence": 0.89,
                                },
                                {
                                    "word": " protègent",
                                    "time_begin": 44.71685,
                                    "time_end": 45.27724,
                                    "confidence": 0.98,
                                },
                                {
                                    "word": " et",
                                    "time_begin": 45.45737,
                                    "time_end": 45.57745,
                                    "confidence": 1,
                                },
                                {
                                    "word": " valorisent",
                                    "time_begin": 45.59746,
                                    "time_end": 46.11783,
                                    "confidence": 0.97,
                                },
                                {
                                    "word": " le",
                                    "time_begin": 46.11783,
                                    "time_end": 46.19788,
                                    "confidence": 1,
                                },
                                {
                                    "word": " domaine",
                                    "time_begin": 46.2179,
                                    "time_end": 46.478080000000006,
                                    "confidence": 0.96,
                                },
                                {
                                    "word": " public.",
                                    "time_begin": 46.518100000000004,
                                    "time_end": 46.87835,
                                    "confidence": 1,
                                },
                            ],
                            "language": "fr",
                            "transcription": "Des outils protègent et valorisent le domaine public.",
                            "confidence": 0.72,
                            "time_begin": 44.25653,
                            "time_end": 46.87835,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " La",
                                    "time_begin": 51.44152,
                                    "time_end": 51.56161,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " mention",
                                    "time_begin": 51.58162,
                                    "time_end": 51.92186,
                                    "confidence": 0.92,
                                },
                                {
                                    "word": " baille,",
                                    "time_begin": 51.9819,
                                    "time_end": 52.30212,
                                    "confidence": 0.86,
                                },
                            ],
                            "language": "fr",
                            "transcription": "La mention baille,",
                            "confidence": 0.72,
                            "time_begin": 51.44152,
                            "time_end": 52.30212,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " qui",
                                    "time_begin": 52.58232,
                                    "time_end": 52.7024,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " impose",
                                    "time_begin": 52.74243,
                                    "time_end": 53.042640000000006,
                                    "confidence": 1,
                                },
                                {
                                    "word": " la",
                                    "time_begin": 53.042640000000006,
                                    "time_end": 53.16272,
                                    "confidence": 1,
                                },
                                {
                                    "word": " citation",
                                    "time_begin": 53.20275,
                                    "time_end": 53.64305,
                                    "confidence": 0.86,
                                },
                                {
                                    "word": " de",
                                    "time_begin": 53.663070000000005,
                                    "time_end": 53.783150000000006,
                                    "confidence": 1,
                                },
                                {
                                    "word": " l'auteur,",
                                    "time_begin": 53.803160000000005,
                                    "time_end": 54.22346,
                                    "confidence": 0.97,
                                },
                            ],
                            "language": "fr",
                            "transcription": "qui impose la citation de l'auteur,",
                            "confidence": 0.72,
                            "time_begin": 52.58232,
                            "time_end": 54.22346,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " est",
                                    "time_begin": 54.48364,
                                    "time_end": 54.60372,
                                    "confidence": 0.86,
                                },
                                {
                                    "word": " obligatoire.",
                                    "time_begin": 54.663759999999996,
                                    "time_end": 55.32422,
                                    "confidence": 0.97,
                                },
                            ],
                            "time_begin": 54.48364,
                            "time_end": 55.32422,
                            "language": "fr",
                            "transcription": "est obligatoire.",
                            "confidence": 0.72,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " L'option",
                                    "time_begin": 58.998020000000004,
                                    "time_end": 59.358360000000005,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " SA",
                                    "time_begin": 59.51851,
                                    "time_end": 59.63862,
                                    "confidence": 1,
                                },
                                {
                                    "word": " indique",
                                    "time_begin": 60.17913,
                                    "time_end": 60.45939,
                                    "confidence": 0.92,
                                },
                                {
                                    "word": " que",
                                    "time_begin": 60.47941,
                                    "time_end": 60.59952,
                                    "confidence": 0.89,
                                },
                                {
                                    "word": " l'œuvre",
                                    "time_begin": 60.61954,
                                    "time_end": 60.8998,
                                    "confidence": 0.98,
                                },
                                {
                                    "word": " doit",
                                    "time_begin": 60.939840000000004,
                                    "time_end": 61.09999,
                                    "confidence": 1,
                                },
                                {
                                    "word": " être",
                                    "time_begin": 61.16005,
                                    "time_end": 61.3202,
                                    "confidence": 1,
                                },
                                {
                                    "word": " partagée",
                                    "time_begin": 61.40027,
                                    "time_end": 61.90074,
                                    "confidence": 0.9,
                                },
                                {
                                    "word": " sous",
                                    "time_begin": 61.980810000000005,
                                    "time_end": 62.100930000000005,
                                    "confidence": 0.98,
                                },
                                {
                                    "word": " la",
                                    "time_begin": 62.12095,
                                    "time_end": 62.241060000000004,
                                    "confidence": 1,
                                },
                                {
                                    "word": " même",
                                    "time_begin": 62.2811,
                                    "time_end": 62.46126,
                                    "confidence": 1,
                                },
                                {
                                    "word": " licence",
                                    "time_begin": 62.52132,
                                    "time_end": 63.04181,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " que",
                                    "time_begin": 63.08185,
                                    "time_end": 63.20196,
                                    "confidence": 1,
                                },
                                {
                                    "word": " celle",
                                    "time_begin": 63.242000000000004,
                                    "time_end": 63.44218,
                                    "confidence": 0.88,
                                },
                                {
                                    "word": " choisie",
                                    "time_begin": 63.48222,
                                    "time_end": 63.7825,
                                    "confidence": 0.93,
                                },
                                {
                                    "word": " par",
                                    "time_begin": 63.822540000000004,
                                    "time_end": 63.94265,
                                    "confidence": 0.97,
                                },
                                {
                                    "word": " l'auteur",
                                    "time_begin": 64.00271000000001,
                                    "time_end": 64.30299,
                                    "confidence": 0.93,
                                },
                                {
                                    "word": " originaire.",
                                    "time_begin": 64.36305,
                                    "time_end": 64.96361,
                                    "confidence": 1,
                                },
                            ],
                            "language": "fr",
                            "transcription": "L'option SA indique que l'œuvre doit être partagée sous la même licence que celle choisie par l'auteur originaire.",
                            "confidence": 0.83,
                            "time_begin": 58.998020000000004,
                            "time_end": 64.96361,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " L'option",
                                    "time_begin": 67.18569,
                                    "time_end": 67.54603,
                                    "confidence": 0.74,
                                },
                                {
                                    "word": " ND",
                                    "time_begin": 67.68616,
                                    "time_end": 67.80627,
                                    "confidence": 0.94,
                                },
                                {
                                    "word": " signifie",
                                    "time_begin": 68.46689,
                                    "time_end": 68.84725,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " que",
                                    "time_begin": 68.86727,
                                    "time_end": 68.98738,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " l'utilisateur",
                                    "time_begin": 69.0074,
                                    "time_end": 69.72808,
                                    "confidence": 0.97,
                                },
                                {
                                    "word": " n'a",
                                    "time_begin": 69.80815,
                                    "time_end": 69.92826,
                                    "confidence": 0.88,
                                },
                                {
                                    "word": " pas",
                                    "time_begin": 70.02836,
                                    "time_end": 70.14847,
                                    "confidence": 0.98,
                                },
                                {
                                    "word": " le",
                                    "time_begin": 70.16849,
                                    "time_end": 70.26858,
                                    "confidence": 1,
                                },
                                {
                                    "word": " droit",
                                    "time_begin": 70.2886,
                                    "time_end": 70.50881,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " de",
                                    "time_begin": 70.50881,
                                    "time_end": 70.62892,
                                    "confidence": 1,
                                },
                                {
                                    "word": " modifier",
                                    "time_begin": 70.64894,
                                    "time_end": 71.08935,
                                    "confidence": 1,
                                },
                                {
                                    "word": " l'œuvre.",
                                    "time_begin": 71.10937,
                                    "time_end": 71.38963,
                                    "confidence": 0.93,
                                },
                            ],
                            "language": "fr",
                            "transcription": "L'option ND signifie que l'utilisateur n'a pas le droit de modifier l'œuvre.",
                            "confidence": 0.83,
                            "time_begin": 67.18569,
                            "time_end": 71.38963,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " L'option",
                                    "time_begin": 75.01303,
                                    "time_end": 75.35335,
                                    "confidence": 0.1,
                                },
                                {
                                    "word": " NC",
                                    "time_begin": 75.47346,
                                    "time_end": 75.63361,
                                    "confidence": 0.49,
                                },
                                {
                                    "word": " interdit",
                                    "time_begin": 76.25419,
                                    "time_end": 76.67459,
                                    "confidence": 0.86,
                                },
                                {
                                    "word": " tout",
                                    "time_begin": 76.69460000000001,
                                    "time_end": 76.83474,
                                    "confidence": 0.96,
                                },
                                {
                                    "word": " usage",
                                    "time_begin": 76.91481,
                                    "time_end": 77.17505,
                                    "confidence": 0.98,
                                },
                                {
                                    "word": " commercial.",
                                    "time_begin": 77.23511,
                                    "time_end": 77.7556,
                                    "confidence": 0.95,
                                },
                            ],
                            "time_begin": 75.01303,
                            "time_end": 77.7556,
                            "language": "fr",
                            "transcription": "L'option NC interdit tout usage commercial.",
                            "confidence": 0.83,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " Ces",
                                    "time_begin": 81.54204,
                                    "time_end": 81.66208999999999,
                                    "confidence": 0.86,
                                },
                                {
                                    "word": " licences",
                                    "time_begin": 81.68209999999999,
                                    "time_end": 82.06226,
                                    "confidence": 0.95,
                                },
                                {
                                    "word": " sont",
                                    "time_begin": 82.12228999999999,
                                    "time_end": 82.24234,
                                    "confidence": 1,
                                },
                                {
                                    "word": " interopérables",
                                    "time_begin": 82.32236999999999,
                                    "time_end": 83.14272,
                                    "confidence": 0.96,
                                },
                                {
                                    "word": " et",
                                    "time_begin": 83.34281,
                                    "time_end": 83.46285999999999,
                                    "confidence": 1,
                                },
                                {
                                    "word": " non",
                                    "time_begin": 83.46285999999999,
                                    "time_end": 83.60292,
                                    "confidence": 0.94,
                                },
                                {
                                    "word": " exclusives.",
                                    "time_begin": 83.64292999999999,
                                    "time_end": 84.32321999999999,
                                    "confidence": 0.95,
                                },
                            ],
                            "language": "fr",
                            "transcription": "Ces licences sont interopérables et non exclusives.",
                            "confidence": 0.82,
                            "time_begin": 81.54204,
                            "time_end": 84.32321999999999,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " Elles",
                                    "time_begin": 86.42411999999999,
                                    "time_end": 86.62419999999999,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " évitent",
                                    "time_begin": 86.68423,
                                    "time_end": 86.96435,
                                    "confidence": 0.9,
                                },
                                {
                                    "word": " des",
                                    "time_begin": 86.96435,
                                    "time_end": 87.08439999999999,
                                    "confidence": 0.93,
                                },
                                {
                                    "word": " coûts",
                                    "time_begin": 87.10440999999999,
                                    "time_end": 87.24445999999999,
                                    "confidence": 0.72,
                                },
                                {
                                    "word": " de",
                                    "time_begin": 87.24445999999999,
                                    "time_end": 87.3245,
                                    "confidence": 0.98,
                                },
                                {
                                    "word": " transaction,",
                                    "time_begin": 87.34451,
                                    "time_end": 87.92474999999999,
                                    "confidence": 1,
                                },
                            ],
                            "language": "fr",
                            "transcription": "Elles évitent des coûts de transaction,",
                            "confidence": 0.82,
                            "time_begin": 86.42411999999999,
                            "time_end": 87.92474999999999,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " fluidifient",
                                    "time_begin": 88.52501,
                                    "time_end": 89.06523999999999,
                                    "confidence": 0.86,
                                },
                                {
                                    "word": " les",
                                    "time_begin": 89.06523999999999,
                                    "time_end": 89.18529,
                                    "confidence": 0.97,
                                },
                                {
                                    "word": " usages",
                                    "time_begin": 89.22531,
                                    "time_end": 89.54544,
                                    "confidence": 1,
                                },
                                {
                                    "word": " numériques",
                                    "time_begin": 89.56545,
                                    "time_end": 90.08567,
                                    "confidence": 0.93,
                                },
                                {
                                    "word": " et",
                                    "time_begin": 91.96646999999999,
                                    "time_end": 92.08652,
                                    "confidence": 0.5,
                                },
                                {
                                    "word": " s'inscrivent",
                                    "time_begin": 92.08652,
                                    "time_end": 92.60673999999999,
                                    "confidence": 0.82,
                                },
                                {
                                    "word": " comme",
                                    "time_begin": 92.62674999999999,
                                    "time_end": 92.76680999999999,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " un",
                                    "time_begin": 92.76680999999999,
                                    "time_end": 92.88686,
                                    "confidence": 0.85,
                                },
                                {
                                    "word": " complément",
                                    "time_begin": 92.90687,
                                    "time_end": 93.36707,
                                    "confidence": 1,
                                },
                                {
                                    "word": " aux",
                                    "time_begin": 93.38707,
                                    "time_end": 93.48711999999999,
                                    "confidence": 0.71,
                                },
                                {
                                    "word": " droits",
                                    "time_begin": 93.48711999999999,
                                    "time_end": 93.68719999999999,
                                    "confidence": 0.87,
                                },
                                {
                                    "word": " d'auteur.",
                                    "time_begin": 93.68719999999999,
                                    "time_end": 94.06736,
                                    "confidence": 0.93,
                                },
                            ],
                            "language": "fr",
                            "transcription": "fluidifient les usages numériques et s'inscrivent comme un complément aux droits d'auteur.",
                            "confidence": 0.82,
                            "time_begin": 88.52501,
                            "time_end": 94.06736,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " Les",
                                    "time_begin": 96.00819,
                                    "time_end": 96.12823999999999,
                                    "confidence": 1,
                                },
                                {
                                    "word": " licences",
                                    "time_begin": 96.14824999999999,
                                    "time_end": 96.54842,
                                    "confidence": 1,
                                },
                                {
                                    "word": " Creative",
                                    "time_begin": 96.56841999999999,
                                    "time_end": 97.00860999999999,
                                    "confidence": 0.89,
                                },
                                {
                                    "word": " Commons",
                                    "time_begin": 97.06863999999999,
                                    "time_end": 97.48881999999999,
                                    "confidence": 0.8,
                                },
                                {
                                    "word": " sont",
                                    "time_begin": 97.80895,
                                    "time_end": 97.94900999999999,
                                    "confidence": 0.95,
                                },
                                {
                                    "word": " compatibles",
                                    "time_begin": 97.96902,
                                    "time_end": 98.52926,
                                    "confidence": 1,
                                },
                                {
                                    "word": " avec",
                                    "time_begin": 98.54926999999999,
                                    "time_end": 98.70933,
                                    "confidence": 1,
                                },
                                {
                                    "word": " le",
                                    "time_begin": 98.70933,
                                    "time_end": 98.82938999999999,
                                    "confidence": 1,
                                },
                                {
                                    "word": " système",
                                    "time_begin": 98.88941,
                                    "time_end": 99.26956999999999,
                                    "confidence": 1,
                                },
                                {
                                    "word": " juridique",
                                    "time_begin": 99.30958999999999,
                                    "time_end": 99.70975999999999,
                                    "confidence": 0.94,
                                },
                                {
                                    "word": " français.",
                                    "time_begin": 99.72976999999999,
                                    "time_end": 100.12993999999999,
                                    "confidence": 0.98,
                                },
                            ],
                            "language": "fr",
                            "transcription": "Les licences Creative Commons sont compatibles avec le système juridique français.",
                            "confidence": 0.82,
                            "time_begin": 96.00819,
                            "time_end": 100.12993999999999,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " Elles",
                                    "time_begin": 102.55096999999999,
                                    "time_end": 102.71103,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " créent",
                                    "time_begin": 102.73104,
                                    "time_end": 103.07119,
                                    "confidence": 0.81,
                                },
                                {
                                    "word": " un",
                                    "time_begin": 103.07119,
                                    "time_end": 103.19124,
                                    "confidence": 0.87,
                                },
                                {
                                    "word": " équilibre",
                                    "time_begin": 103.21124999999999,
                                    "time_end": 103.65142999999999,
                                    "confidence": 1,
                                },
                                {
                                    "word": " entre",
                                    "time_begin": 103.71145999999999,
                                    "time_end": 103.91153999999999,
                                    "confidence": 1,
                                },
                                {
                                    "word": " les",
                                    "time_begin": 103.95156,
                                    "time_end": 104.07160999999999,
                                    "confidence": 1,
                                },
                                {
                                    "word": " droits",
                                    "time_begin": 104.09161999999999,
                                    "time_end": 104.31170999999999,
                                    "confidence": 0.95,
                                },
                                {
                                    "word": " des",
                                    "time_begin": 104.31170999999999,
                                    "time_end": 104.43176,
                                    "confidence": 1,
                                },
                                {
                                    "word": " créateurs",
                                    "time_begin": 104.43176,
                                    "time_end": 105.03201999999999,
                                    "confidence": 0.97,
                                },
                                {
                                    "word": " et",
                                    "time_begin": 105.27212,
                                    "time_end": 105.39217,
                                    "confidence": 1,
                                },
                                {
                                    "word": " ceux",
                                    "time_begin": 105.45219999999999,
                                    "time_end": 105.57225,
                                    "confidence": 0.87,
                                },
                                {
                                    "word": " des",
                                    "time_begin": 105.63226999999999,
                                    "time_end": 105.75233,
                                    "confidence": 1,
                                },
                                {
                                    "word": " utilisateurs.",
                                    "time_begin": 105.81235,
                                    "time_end": 106.55266999999999,
                                    "confidence": 0.99,
                                },
                            ],
                            "time_begin": 102.55096999999999,
                            "time_end": 106.55266999999999,
                            "language": "fr",
                            "transcription": "Elles créent un équilibre entre les droits des créateurs et ceux des utilisateurs.",
                            "confidence": 0.82,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " Aujourd'hui,",
                                    "time_begin": 110.91017,
                                    "time_end": 111.29123999999999,
                                    "confidence": 0.98,
                                }
                            ],
                            "language": "fr",
                            "transcription": "Aujourd'hui,",
                            "confidence": 0.72,
                            "time_begin": 110.91017,
                            "time_end": 111.29123999999999,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                        {
                            "words": [
                                {
                                    "word": " il",
                                    "time_begin": 111.89294,
                                    "time_end": 112.01328,
                                    "confidence": 1,
                                },
                                {
                                    "word": " est",
                                    "time_begin": 111.99322,
                                    "time_end": 112.09349999999999,
                                    "confidence": 0.94,
                                },
                                {
                                    "word": " possible",
                                    "time_begin": 112.11355999999999,
                                    "time_end": 112.51468999999999,
                                    "confidence": 1,
                                },
                                {
                                    "word": " d'accéder",
                                    "time_begin": 112.53474999999999,
                                    "time_end": 112.99605,
                                    "confidence": 0.93,
                                },
                                {
                                    "word": " à",
                                    "time_begin": 113.0161,
                                    "time_end": 113.07627,
                                    "confidence": 1,
                                },
                                {
                                    "word": " des",
                                    "time_begin": 113.09633,
                                    "time_end": 113.21667,
                                    "confidence": 1,
                                },
                                {
                                    "word": " millions",
                                    "time_begin": 113.27683999999999,
                                    "time_end": 113.69802,
                                    "confidence": 0.99,
                                },
                                {
                                    "word": " de",
                                    "time_begin": 113.69802,
                                    "time_end": 113.81836,
                                    "confidence": 1,
                                },
                                {
                                    "word": " contenus",
                                    "time_begin": 113.83842,
                                    "time_end": 114.37993999999999,
                                    "confidence": 0.65,
                                },
                                {
                                    "word": " et",
                                    "time_begin": 114.42005999999999,
                                    "time_end": 114.54039999999999,
                                    "confidence": 1,
                                },
                                {
                                    "word": " de",
                                    "time_begin": 114.52033999999999,
                                    "time_end": 114.64067999999999,
                                    "confidence": 1,
                                },
                                {
                                    "word": " données",
                                    "time_begin": 114.66073,
                                    "time_end": 115.00169,
                                    "confidence": 0.8,
                                },
                                {
                                    "word": " sous",
                                    "time_begin": 115.3226,
                                    "time_end": 115.44294,
                                    "confidence": 0.96,
                                },
                                {
                                    "word": " licence",
                                    "time_begin": 115.48304999999999,
                                    "time_end": 115.84406999999999,
                                    "confidence": 0.84,
                                },
                                {
                                    "word": " Creative",
                                    "time_begin": 115.86412,
                                    "time_end": 116.30537,
                                    "confidence": 0.88,
                                },
                                {
                                    "word": " Commons.",
                                    "time_begin": 116.36554,
                                    "time_end": 116.76666999999999,
                                    "confidence": 0.83,
                                },
                            ],
                            "time_begin": 111.89294,
                            "time_end": 116.76666999999999,
                            "language": "fr",
                            "transcription": "il est possible d'accéder à des millions de contenus et de données sous licence Creative Commons.",
                            "confidence": 0.72,
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                        },
                    ],
                    "metadata": {
                        "provided_file_metadata": {
                            "sample_rate": 44100,
                            "duration": 122.122449,
                            "nb_channels": 2,
                            "sample_width": 0,
                            "original_file_type": "audio",
                            "number_similar_channels": 1,
                        },
                        "nb_silent_channels": -1,
                        "total_speech_duration": 66.53934999999997,
                        "audio_conversion_time": 5.021551609039307,
                        "vad_time": 0.15980911254882812,
                        "inference_time": 10.841955661773682,
                        "translation_time": 4.76837158203125e-7,
                        "emotion_time": 4.76837158203125e-7,
                        "summarization_time": 2.384185791015625e-7,
                        "chapterization_time": 4.76837158203125e-7,
                        "total_transcription_time": 16.0600802898407,
                    },
                    "speaker_mapping": [
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 9.476939999999999,
                            "time_end": 13.680810000000001,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 15.78274,
                            "time_end": 19.40607,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 19.52618,
                            "time_end": 20.24684,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 22.74914,
                            "time_end": 24.931150000000002,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 25.511680000000002,
                            "time_end": 31.23694,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 34.91004,
                            "time_end": 39.15299,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 39.59329,
                            "time_end": 43.35591,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 44.25653,
                            "time_end": 46.87835,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 51.44152,
                            "time_end": 52.30212,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 52.58232,
                            "time_end": 54.22346,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 54.48364,
                            "time_end": 55.32422,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 58.998020000000004,
                            "time_end": 64.96361,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 67.18569,
                            "time_end": 71.38963,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 75.01303,
                            "time_end": 77.7556,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 81.54204,
                            "time_end": 84.32321999999999,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 86.42411999999999,
                            "time_end": 87.92474999999999,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 88.52501,
                            "time_end": 94.06736,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 96.00819,
                            "time_end": 100.12993999999999,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 102.55096999999999,
                            "time_end": 106.55266999999999,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 110.91017,
                            "time_end": 111.29123999999999,
                        },
                        {
                            "speaker": "speaker_not_activated",
                            "channel": "channel_0",
                            "time_begin": 111.89294,
                            "time_end": 116.76666999999999,
                        },
                    ],
                },
            },
        }
        response = self.client.post(
            f"/api/videos/{timed_text_track.video.pk}/timedtexttracks/"
            f"{timed_text_track.id}/transcript-callback/",
            content_type="application/json",
            data=data,
        )

        self.assertEqual(response.status_code, 200)
        s3_storage = storages["s3"]
        timed_text_track.refresh_from_db()
        transcript = s3_storage.open(timed_text_track.get_source_s3_key(), mode="r")
        self.assertEqual(transcript.read(), data["payload"]["prediction"])
