# Generated by Django 4.0.4 on 2022-05-23 15:01

import uuid

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0051_migrate_live_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdpOrganizationAssociation",
            fields=[
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "idp_identifier",
                    models.CharField(
                        db_index=True,
                        help_text="allows to know which IdP is linked (eg. the Entity ID for SAML)",
                        max_length=255,
                        verbose_name="identity provider ID",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="organization linked to the identity provider",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_providers",
                        to="core.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "db_table": "idp_organization_association",
                "unique_together": {("idp_identifier", "organization")},
            },
        ),
    ]
