# Generated by Django 4.0.7 on 2022-09-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="idporganizationassociation",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="idporganizationassociation",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="idporganizationassociation",
            name="idp_identifier",
            field=models.CharField(
                db_index=True,
                help_text="allows to know which IdP is linked (eg. the Entity ID for SAML)",
                max_length=255,
                unique=True,
                verbose_name="identity provider ID",
            ),
        ),
    ]
