# Generated by Django 4.0.4 on 2022-05-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markdown", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="markdowndocument",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
