# Generated by Django 4.0.6 on 2022-08-18 16:16

import uuid

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("markdown", "0002_markdowndocument_deleted_by_cascade"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkdownImage",
            fields=[
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "uploaded_on",
                    models.DateTimeField(
                        blank=True,
                        help_text="datetime at which the active version of the file was uploaded.",
                        null=True,
                        verbose_name="uploaded on",
                    ),
                ),
                (
                    "upload_state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("error", "error"),
                            ("ready", "ready"),
                            ("deleted", "deleted"),
                        ],
                        default="pending",
                        help_text="state of the upload in AWS.",
                        max_length=20,
                        verbose_name="upload state",
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text='image extension (like "png", "jpg", etc.',
                        max_length=10,
                        null=True,
                        verbose_name="file extension",
                    ),
                ),
                (
                    "markdown_document",
                    models.ForeignKey(
                        help_text="markdown document using this image",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="markdown.markdowndocument",
                        verbose_name="Markdown document",
                    ),
                ),
            ],
            options={
                "verbose_name": "image",
                "db_table": "md_images",
                "ordering": ["-created_on", "id"],
            },
        ),
    ]
