# Generated by Django 4.0.7 on 2022-09-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markdown", "0003_markdownimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markdowndocument",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="markdownimage",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="markdownimage",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                    ("deleted", "deleted"),
                    ("scanning", "scanning"),
                    ("infected", "infected"),
                    ("copying", "copying"),
                ],
                default="pending",
                help_text="state of the upload in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
    ]
