# Generated by Django 4.0.7 on 2022-09-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markdown", "0004_alter_markdowndocument_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markdownimage",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("initialized", "initialized"),
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                    ("deleted", "deleted"),
                    ("scanning", "scanning"),
                    ("infected", "infected"),
                    ("copying", "copying"),
                ],
                default="pending",
                help_text="state of the upload in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
    ]
