# Generated by Django 5.0.9 on 2025-05-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markdown", "0006_alter_markdowndocumenttranslation_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="markdownimage",
            name="storage_location",
            field=models.CharField(
                choices=[("AWS", "AWS"), ("SCW", "SCW")],
                default="SCW",
                help_text="Location used to store the Markdown image",
                max_length=255,
                verbose_name="storage location",
            ),
        ),
    ]
