# Generated by Django 4.1.9 on 2023-06-13 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("markdown", "0006_alter_markdowndocumenttranslation_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markdowndocument",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                help_text="author of the file",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
            preserve_default=False,
        ),
    ]
