# Generated by Django 5.0.9 on 2025-07-09 07:14

from django.db import migrations

from marsha.core.defaults import AWS_S3


def fix_storage_location_to_aws(apps, schema_editor):
    """Fix the storage_location field for existing markdown images on AWS."""
    MarkdownImage = apps.get_model("markdown", "MarkdownImage")
    MarkdownImage.objects.filter(storage_location="AWS_S3").update(
        storage_location=AWS_S3
    )


class Migration(migrations.Migration):
    dependencies = [
        ("markdown", "0008_markdownimage_fill_storage_location"),
    ]

    operations = [
        migrations.RunPython(fix_storage_location_to_aws, migrations.RunPython.noop),
    ]
