# Generated by Django 4.0.2 on 2022-02-16 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_auto_20220119_0955"),
        ("bbb", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="started_on",
        ),
        migrations.AddField(
            model_name="meeting",
            name="ended",
            field=models.BooleanField(default=False),
        ),
    ]
