# Generated by Django 4.0.3 on 2022-03-31 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0002_remove_meeting_started_on_meeting_ended_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="title of the meeting",
                max_length=255,
                null=True,
                verbose_name="title",
            ),
        ),
    ]
