# Generated by Django 4.0.3 on 2022-04-07 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0003_alter_meeting_moderator_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="estimated_duration",
            field=models.DurationField(
                blank=True,
                help_text="Estimated duration of the meeting in seconds.",
                null=True,
                verbose_name="estimated duration",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="starting_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Start date and time at which a meeting is scheduled.",
                null=True,
                verbose_name="starting at date and time",
            ),
        ),
    ]
