# Generated by Django 4.0.4 on 2022-05-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0004_meeting_estimated_duration_meeting_starting_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
