# Generated by Django 4.0.5 on 2022-06-08 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_noop_run_missing_migrations"),
        ("bbb", "0005_meeting_deleted_by_cascade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="moderator_password",
            field=models.CharField(
                blank=True,
                help_text="The password that the join URL can later provide as its password parameter to indicate the user will join as a moderator.",
                max_length=50,
                null=True,
                verbose_name="Moderator Password",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="playlist",
            field=models.ForeignKey(
                help_text="playlist to which this meeting belongs",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="core.playlist",
                verbose_name="playlist",
            ),
        ),
    ]
