# Generated by Django 4.0.7 on 2022-09-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0007_classroom_rename_meeting_to_classroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
    ]
