# Generated by Django 4.0.7 on 2022-09-26 09:58

import uuid

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0008_alter_classroom_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassroomDocument",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "uploaded_on",
                    models.DateTimeField(
                        blank=True,
                        help_text="datetime at which the active version of the file was uploaded.",
                        null=True,
                        verbose_name="uploaded on",
                    ),
                ),
                (
                    "upload_state",
                    models.CharField(
                        choices=[
                            ("initialized", "initialized"),
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("error", "error"),
                            ("ready", "ready"),
                            ("deleted", "deleted"),
                            ("scanning", "scanning"),
                            ("infected", "infected"),
                            ("copying", "copying"),
                        ],
                        default="pending",
                        help_text="state of the upload in AWS.",
                        max_length=20,
                        verbose_name="upload state",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True,
                        help_text="filename of the classroom document",
                        max_length=255,
                        null=True,
                        verbose_name="filename",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="is displayed by default in the classroom",
                        verbose_name="is default",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        help_text="clasroom to which this document belongs",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classroom_documents",
                        to="bbb.classroom",
                        verbose_name="classroom document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classroom document",
                "verbose_name_plural": "Classroom documents",
                "db_table": "classroom_document",
                "ordering": ["-uploaded_on"],
            },
        ),
    ]
