# Generated by Django 4.0.8 on 2023-01-12 10:33

import uuid

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0010_alter_classroom_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassroomRecording",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "record_id",
                    models.CharField(
                        editable=False,
                        help_text="BBB meeting id",
                        max_length=255,
                        unique=True,
                        verbose_name="BBB record id",
                    ),
                ),
                (
                    "video_file_url",
                    models.CharField(
                        blank=True,
                        help_text="url of the classroom recording",
                        max_length=255,
                        null=True,
                        verbose_name="video url",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start date and time of the record.",
                        null=True,
                        verbose_name="Recording started at date and time",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        help_text="classroom to which this recording belongs",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recordings",
                        to="bbb.classroom",
                        verbose_name="classroom recording",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classroom recording",
                "verbose_name_plural": "Classroom recordings",
                "db_table": "classroom_recording",
                "ordering": ["-created_on"],
            },
        ),
    ]
