# Generated by Django 4.1.7 on 2023-04-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0012_alter_classroomdocument_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="enable_waiting_room",
            field=models.BooleanField(
                default=False,
                help_text="Enable or not waiting room for the classroom",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="enable_shared_notes",
            field=models.BooleanField(
                default=True,
                help_text="Enable or not the shared notes option for the classroom",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="enable_chat",
            field=models.BooleanField(
                default=True, help_text="Enable or not the chat for the classroom"
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="enable_presentation_supports",
            field=models.BooleanField(
                default=True,
                help_text="Allow or not to share documents with the classroom",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="enable_recordings",
            field=models.BooleanField(
                default=True, help_text="Enable or not to record the classroom sessions"
            ),
        ),
    ]
