# Generated by Django 4.1.7 on 2023-04-20 15:49

import uuid

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0013_classroom_tools_parameters"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassroomSharedNote",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the shared note as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="date and time at which a shared note was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a shared note was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "shared_note_url",
                    models.CharField(
                        blank=True,
                        help_text="url of the classroom shared note",
                        max_length=255,
                        null=True,
                        verbose_name="shared note url",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        help_text="classroom to which this shared note belongs",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shared notes",
                        to="bbb.classroom",
                        verbose_name="classroom shared note",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classroom shared note",
                "verbose_name_plural": "Classroom shared notes",
                "db_table": "classroom_shared_note",
                "ordering": ["-updated_on"],
            },
        ),
    ]
