# Generated by Django 4.1.9 on 2023-05-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0013_classroom_tools_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroomrecording",
            name="classroom",
            field=models.ForeignKey(
                help_text="classroom to which this recording belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordings",
                to="bbb.classroom",
                verbose_name="classroom recording",
            ),
        ),
        migrations.AlterField(
            model_name="classroomdocument",
            name="classroom",
            field=models.ForeignKey(
                help_text="clasroom to which this document belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_documents",
                to="bbb.classroom",
                verbose_name="classroom document",
            ),
        ),
    ]
