# Generated by Django 4.1.7 on 2023-05-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0015_classroomrecording_vod"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="recording_purpose",
            field=models.TextField(
                blank=True,
                help_text="A text to explain what is the record purpose",
                null=True,
                verbose_name="record purpose",
            ),
        ),
    ]
