# Generated by Django 4.1.9 on 2023-06-07 11:31

import secrets

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0017_classroom_recording_vod_delete_cascade"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="instructor_token",
            field=models.CharField(
                default=secrets.token_urlsafe,
                help_text="instructor token used in invitation link",
                max_length=255,
                verbose_name="instructor token",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="public_token",
            field=models.CharField(
                default=secrets.token_urlsafe,
                help_text="public token used in invitation link",
                max_length=255,
                verbose_name="public token",
            ),
        ),
    ]
