# Generated by Django 4.1.9 on 2023-06-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0018_classroom_instructor_token_classroom_public_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="retention_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the video and its related resources should be deleted",
                null=True,
                verbose_name="retention date",
            ),
        ),
    ]
