# Generated by Django 4.2.3 on 2023-07-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0019_add_retention_date_to_classroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroomrecording",
            name="video_file_url",
            field=models.CharField(
                blank=True,
                db_column="video_file_url",
                help_text="url of the classroom recording",
                max_length=255,
                null=True,
                verbose_name="video url",
            ),
        ),
        migrations.RenameField(
            model_name="classroomrecording",
            old_name="video_file_url",
            new_name="_video_file_url",
        ),
    ]
