# Generated by Django 4.2.5 on 2023-10-04 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0020_alter_classroomrecording_video_file_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="retention_date",
            field=models.DateField(
                blank=True,
                help_text="Date when this playlist related object should be deleted",
                null=True,
                verbose_name="retention date",
            ),
        ),
        migrations.AlterField(
            model_name="classroomdocument",
            name="classroom",
            field=models.ForeignKey(
                help_text="classroom to which this document belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_documents",
                to="bbb.classroom",
                verbose_name="classroom document",
            ),
        ),
    ]
