# Generated by Django 4.2.6 on 2023-10-18 11:12

import uuid

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0021_noop_alter_classroom_retention_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassroomSession",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "cookie",
                    models.JSONField(
                        help_text="BBB session cookie",
                        verbose_name="BBB session cookie",
                    ),
                ),
                (
                    "bbb_learning_analytics_url",
                    models.CharField(
                        help_text="BBB learning analytics url",
                        max_length=255,
                        verbose_name="BBB learning analytics url",
                    ),
                ),
                (
                    "learning_analytics",
                    models.JSONField(
                        blank=True,
                        help_text="Classroom session learning analytics",
                        null=True,
                        verbose_name="Classroom session learning analytics",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Start date and time of the session.",
                        verbose_name="Session started at date and time",
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="End date and time of the session.",
                        null=True,
                        verbose_name="Session ended at date and time",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        help_text="classroom to which this session belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="bbb.classroom",
                        verbose_name="classroom session",
                    ),
                ),
            ],
            options={
                "db_table": "classroom_session",
            },
        ),
        migrations.AddConstraint(
            model_name="classroomsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("classroom",),
                name="classroom_session_unique_not_ended",
            ),
        ),
    ]
