# Generated by Django 4.2.6 on 2023-10-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0022_classroomsession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="infos",
            field=models.JSONField(
                blank=True,
                help_text="BBB meeting infos",
                null=True,
                verbose_name="BBB meeting infos",
            ),
        ),
    ]
