# Generated by Django 5.0.9 on 2025-04-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bbb", "0023_classroom_infos"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomdocument",
            name="storage_location",
            field=models.CharField(
                choices=[("AWS", "AWS"), ("SCW", "SCW")],
                default="SCW",
                help_text="Location used to store the classroom document",
                max_length=255,
                verbose_name="storage location",
            ),
        ),
    ]
