# Generated by Django 5.0.9 on 2025-06-11 17:34

from django.db import migrations

from marsha.core.defaults import AWS_S3


def fix_storage_location_to_aws(apps, schema_editor):
    """Update the storage_location field for existing classroom documents."""
    ClassroomDocument = apps.get_model("bbb", "ClassroomDocument")
    ClassroomDocument.objects.filter(storage_location="AWS_S3").update(
        storage_location=AWS_S3
    )


class Migration(migrations.Migration):
    dependencies = [
        ("bbb", "0025_classroomdocument_fill_storage_location"),
    ]

    operations = [
        migrations.RunPython(fix_storage_location_to_aws, migrations.RunPython.noop),
    ]
