# Generated by Django 4.2 on 2023-04-26 09:46

import uuid

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Page slug (/page/{slug})",
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Page displayed name",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Content of the page in Markdown format",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Is the page ready to be shown publicly",
                        verbose_name="is published",
                    ),
                ),
            ],
            options={
                "verbose_name": "page",
                "verbose_name_plural": "page",
                "db_table": "page",
                "ordering": ["created_on"],
            },
        ),
    ]
