# Generated by Django 4.2.3 on 2023-07-05 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("page", "0001_initial_page_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="sites.site",
                verbose_name="site",
            ),
        ),
    ]
