[tool.ruff]
line-length = 100

select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "UP",  # pyupgrade,
  "I",   # isort
]

[build-system]
requires = ["django", "djangorestframework", "ruff", "ffmpeg-python", "python-socketio"]
