# Generated by Django 4.2.4 on 2023-08-28 09:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Runner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("runnerToken", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(max_length=255, null=True)),
                ("lastContact", models.DateTimeField()),
                ("ip", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RunnerRegistrationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registrationToken", models.CharField(max_length=255, unique=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (1, "Published"),
                            (2, "To transcode"),
                            (3, "To import"),
                            (4, "Waiting for live"),
                            (5, "Live ended"),
                            (6, "To move to external storage"),
                            (7, "Transcoding failed"),
                            (8, "To move to external storage failed"),
                            (9, "To edit"),
                        ]
                    ),
                ),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "thumbnailFilename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="VideoStreamingPlaylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "playlistFilename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streamingPlaylist",
                        to="transcoding.video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoJobInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pendingMove", models.IntegerField(default=0)),
                ("pendingTranscode", models.IntegerField(default=0)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobInfo",
                        to="transcoding.video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resolution",
                    models.IntegerField(
                        choices=[
                            (0, "H Novideo"),
                            (144, "H 144P"),
                            (240, "H 240P"),
                            (360, "H 360P"),
                            (480, "H 480P"),
                            (720, "H 720P"),
                            (1080, "H 1080P"),
                            (1440, "H 1440P"),
                            (2160, "H 4K"),
                        ]
                    ),
                ),
                ("size", models.BigIntegerField()),
                ("extname", models.CharField(max_length=255)),
                ("fps", models.IntegerField(default=-1)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "streamingPlaylist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videoFiles",
                        to="transcoding.videostreamingplaylist",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="transcoding.video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunnerJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vod-web-video-transcoding", "Vod Web Video Transcoding"),
                            ("vod-hls-transcoding", "Vod Hls Transcoding"),
                            (
                                "vod-audio-merge-transcoding",
                                "Vod Audio Merge Transcoding",
                            ),
                            ("live-rtmp-hls-transcoding", "Live Rtmp Hls Transcoding"),
                            ("video-studio-transcoding", "Video Studio Transcoding"),
                        ],
                        max_length=255,
                    ),
                ),
                ("payload", models.JSONField()),
                ("privatePayload", models.JSONField()),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (1, "Pending"),
                            (2, "Processing"),
                            (3, "Completed"),
                            (4, "Errored"),
                            (5, "Waiting for parent job"),
                            (6, "Cancelled"),
                            (7, "Parent errored"),
                            (8, "Parent cancelled"),
                            (9, "Completing"),
                        ]
                    ),
                ),
                ("failures", models.IntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=255, null=True)),
                ("priority", models.IntegerField()),
                (
                    "processingJobToken",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("progress", models.FloatField(blank=True, null=True)),
                ("startedAt", models.DateTimeField(blank=True, null=True)),
                ("finishedAt", models.DateTimeField(blank=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "dependsOnRunnerJob",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transcoding.runnerjob",
                    ),
                ),
                (
                    "runner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transcoding.runner",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="runner",
            name="runnerRegistrationToken",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transcoding.runnerregistrationtoken",
            ),
        ),
    ]
