# Generated by Django 2.0 on 2018-09-13 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="video",
            name="uploaded_on",
            field=models.DateTimeField(
                blank=True,
                help_text="datetime at which the active version of the video was uploaded.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="uploaded on",
            ),
        )
    ]
