# Generated by Django 2.0 on 2019-01-12 10:43

from django.db import migrations

import marsha.core.models.base


class Migration(migrations.Migration):
    dependencies = [("core", "0003_auto_20190108_1712")]

    operations = [
        migrations.AddIndex(
            model_name="playlist",
            index=marsha.core.models.base.NonDeletedUniqueIndex(
                fields=["lti_id", "consumer_site"], name="playlist_lti_id_5806ef_idx"
            ),
        )
    ]
