# Generated by Django 2.0 on 2019-01-12 10:46

from django.db import migrations

import marsha.core.models.base


class Migration(migrations.Migration):
    dependencies = [("core", "0004_auto_20190112_1043")]

    operations = [
        migrations.AddIndex(
            model_name="video",
            index=marsha.core.models.base.NonDeletedUniqueIndex(
                fields=["lti_id", "playlist"], name="video_lti_id_bc7766_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=marsha.core.models.base.NonDeletedUniqueIndex(
                fields=["resource_id", "playlist"], name="video_resourc_74f11b_idx"
            ),
        ),
    ]
