# Generated by Django 2.0 on 2019-01-14 16:50

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import marsha.core.models.base


class Migration(migrations.Migration):
    dependencies = [("core", "0005_auto_20190112_1046")]

    operations = [
        migrations.CreateModel(
            name="ConsumerSitePortability",
            fields=[
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
            ],
            options={
                "verbose_name": "consumer site portability",
                "verbose_name_plural": "consumer site portabilities",
                "db_table": "consumersite_portability",
            },
        ),
        migrations.AlterField(
            model_name="audiotrack",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                ],
                default="pending",
                help_text="state of the upload and transcoding pipeline in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
        migrations.AlterField(
            model_name="consumersite",
            name="name",
            field=models.CharField(
                help_text="name of the consumer site.",
                max_length=50,
                verbose_name="display name",
            ),
        ),
        migrations.AlterField(
            model_name="consumersite",
            name="users",
            field=models.ManyToManyField(
                help_text="users who have been granted access to this consumer site.",
                through="core.ConsumerSiteAccess",
                to=settings.AUTH_USER_MODEL,
                verbose_name="users",
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="duplicated_from",
            field=models.ForeignKey(
                blank=True,
                help_text="original playlist this one was duplicated from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="core.Playlist",
                verbose_name="duplicated from",
            ),
        ),
        migrations.AlterField(
            model_name="signtrack",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                ],
                default="pending",
                help_text="state of the upload and transcoding pipeline in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
        migrations.AlterField(
            model_name="timedtexttrack",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                ],
                default="pending",
                help_text="state of the upload and transcoding pipeline in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="duplicated_from",
            field=models.ForeignKey(
                blank=True,
                help_text="original video this one was duplicated from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="core.Video",
                verbose_name="duplicated from",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                ],
                default="pending",
                help_text="state of the upload and transcoding pipeline in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
        migrations.AddField(
            model_name="consumersiteportability",
            name="source_site",
            field=models.ForeignKey(
                help_text="consumer site that is portable.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portable_to_links",
                to="core.ConsumerSite",
                verbose_name="source site",
            ),
        ),
        migrations.AddField(
            model_name="consumersiteportability",
            name="target_site",
            field=models.ForeignKey(
                help_text="consumer site to which portability is automatic.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reachable_from_links",
                to="core.ConsumerSite",
                verbose_name="target site",
            ),
        ),
        migrations.AddField(
            model_name="consumersite",
            name="portable_to",
            field=models.ManyToManyField(
                blank=True,
                help_text="Consumer sites to which this site is automatically portable.",
                related_name="reachable_from",
                through="core.ConsumerSitePortability",
                to="core.ConsumerSite",
                verbose_name="portable to",
            ),
        ),
        migrations.AddIndex(
            model_name="consumersiteportability",
            index=marsha.core.models.base.NonDeletedUniqueIndex(
                fields=["source_site", "target_site"],
                name="consumersit_source__894f0f_idx",
            ),
        ),
    ]
