# Generated by Django 2.0 on 2018-10-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0005_video_resource_id")]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="is_portable_to_consumer_site",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playlist",
            name="is_portable_to_playlist",
            field=models.BooleanField(default=True),
        ),
    ]
