# Generated by Django 2.0 on 2019-01-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0006_auto_20190114_1650")]

    operations = [
        migrations.RemoveIndex(model_name="video", name="video_resourc_74f11b_idx"),
        migrations.RemoveField(model_name="video", name="resource_id"),
        migrations.AlterField(
            model_name="consumersite",
            name="portable_to",
            field=models.ManyToManyField(
                blank=True,
                help_text="consumer sites to which this site is automatically portable.",
                related_name="reachable_from",
                through="core.ConsumerSitePortability",
                to="core.ConsumerSite",
                verbose_name="portable to",
            ),
        ),
    ]
