# Generated by Django 2.0 on 2019-01-22 11:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0006_auto_20190114_1650")]

    operations = [
        migrations.RemoveIndex(model_name="video", name="video_resourc_74f11b_idx"),
        # Make resource_id nullable so it can be removed from our code (it will be removed
        # from database in a separate release to ensure compatibility with the previous release
        # running in production)
        migrations.AlterField(
            model_name="video",
            name="resource_id",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                help_text="UUID to identify the resource in the backend",
                null=True,
                verbose_name="Resource UUID",
            ),
        ),
    ]
