# Generated by Django 2.0 on 2018-10-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0006_auto_20181004_0909")]

    operations = [
        migrations.AlterField(
            model_name="audiotrack",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                ],
                default="pending",
                help_text="state of the upload and transcoding pipeline in AWS.",
                max_length=20,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="signtrack",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                ],
                default="pending",
                help_text="state of the upload and transcoding pipeline in AWS.",
                max_length=20,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="subtitletrack",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                ],
                default="pending",
                help_text="state of the upload and transcoding pipeline in AWS.",
                max_length=20,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                ],
                default="pending",
                help_text="state of the upload and transcoding pipeline in AWS.",
                max_length=20,
                verbose_name="state",
            ),
        ),
    ]
