# Generated by Django 2.0 on 2018-11-20 17:42

from django.db import migrations, models

import marsha.core.models.base


class Migration(migrations.Migration):

    dependencies = [("core", "0007_auto_20181009_1631")]

    operations = [
        migrations.RemoveIndex(
            model_name="subtitletrack", name="subtitle_tr_video_i_7ef2a4_idx"
        ),
        migrations.RemoveField(
            model_name="subtitletrack", name="has_closed_captioning"
        ),
        migrations.AddField(
            model_name="subtitletrack",
            name="mode",
            field=models.CharField(
                blank=True,
                choices=[("ts", "Transcript"), ("cc", "Closed captioning")],
                help_text="Activate a special mode for this subtitle track: closed captioning (for deaf or hard of hearing viewers) or transcription (complete text below aside of the player).",
                max_length=2,
                null=True,
                verbose_name="mode",
            ),
        ),
        migrations.AddIndex(
            model_name="subtitletrack",
            index=marsha.core.models.base.NonDeletedUniqueIndex(
                fields=["video", "language", "mode"],
                name="subtitle_tr_video_i_00108b_idx",
            ),
        ),
    ]
