# Generated by Django 2.0 on 2019-04-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0010_auto_20190329_0825")]

    operations = [
        migrations.AddField(
            model_name="consumersite",
            name="lrs_auth_token",
            field=models.TextField(
                blank=True,
                help_text="LRS authentication token used to communicate with a remote LRS",
                verbose_name="LRS authentication token",
            ),
        ),
        migrations.AddField(
            model_name="consumersite",
            name="lrs_url",
            field=models.CharField(
                blank=True,
                help_text="LRS url used to communicate with a remote LRS",
                max_length=150,
                verbose_name="LRS url",
            ),
        ),
        migrations.AddField(
            model_name="consumersite",
            name="lrs_xapi_version",
            field=models.CharField(
                blank=True,
                help_text="xAPI version used by the remote LRS server",
                max_length=10,
                verbose_name="xAPI version",
            ),
        ),
    ]
