# Generated by Django 2.0 on 2019-04-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0011_auto_20190417_0925")]

    operations = [
        migrations.AddField(
            model_name="consumersite",
            name="video_show_download_default",
            field=models.BooleanField(
                default=True,
                help_text="default value used for every newly created video to determine if the links to download a video are shown by default.",
                verbose_name="show video download",
            ),
        )
    ]
