# Generated by Django 2.2.1 on 2019-05-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0012_auto_20190418_0755")]

    operations = [
        migrations.RemoveIndex(
            model_name="audiotrack", name="audio_track_video_i_fe6276_idx"
        ),
        migrations.RemoveIndex(
            model_name="consumersiteaccess", name="consumersit_user_id_f9d219_idx"
        ),
        migrations.RemoveIndex(
            model_name="consumersiteorganization", name="consumersit_consume_89f4d1_idx"
        ),
        migrations.RemoveIndex(
            model_name="consumersiteportability", name="consumersit_source__894f0f_idx"
        ),
        migrations.RemoveIndex(
            model_name="organizationaccess", name="organizatio_user_id_d0a5d6_idx"
        ),
        migrations.RemoveIndex(
            model_name="playlist", name="playlist_lti_id_5806ef_idx"
        ),
        migrations.RemoveIndex(
            model_name="playlistaccess", name="playlist_ac_user_id_c7df1b_idx"
        ),
        migrations.RemoveIndex(
            model_name="signtrack", name="sign_track_video_i_8ae92b_idx"
        ),
        migrations.RemoveIndex(
            model_name="timedtexttrack", name="timed_text__video_i_1425f7_idx"
        ),
        migrations.RemoveIndex(model_name="video", name="video_lti_id_bc7766_idx"),
        migrations.AddConstraint(
            model_name="audiotrack",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted=None),
                fields=("video", "language"),
                name="audio_track_unique_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="consumersiteaccess",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted=None),
                fields=("user", "consumer_site"),
                name="consumersite_access_unique_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="consumersiteorganization",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted=None),
                fields=("consumer_site", "organization"),
                name="consumersite_organization_unique_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="consumersiteportability",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted=None),
                fields=("source_site", "target_site"),
                name="consumersite_portability_unique_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationaccess",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted=None),
                fields=("user", "organization"),
                name="organization_access_unique_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="playlist",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted=None),
                fields=("lti_id", "consumer_site"),
                name="playlist_unique_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="playlistaccess",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted=None),
                fields=("user", "playlist"),
                name="playlist_access_unique_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="signtrack",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted=None),
                fields=("video", "language"),
                name="sign_track_unique_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="timedtexttrack",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted=None),
                fields=("video", "language", "mode"),
                name="timed_text_track_unique_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="video",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted=None),
                fields=("lti_id", "playlist"),
                name="video_unique_idx",
            ),
        ),
    ]
