# Generated by Django 2.2.4 on 2019-09-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0014_auto_20190523_1004")]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extension",
            field=models.CharField(
                default=None,
                help_text="file extension",
                max_length=10,
                null=True,
                verbose_name="extension",
                blank=True,
            ),
        )
    ]
