# Generated by Django 3.0.6 on 2020-06-03 06:20

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


def initialize_video_resolutions(apps, schema_editor):
    """
    Insert default sizes in the new resolutions field
    """
    Video = apps.get_model("core", "Video")
    Video.objects.filter(resolutions__isnull=True).update(
        resolutions=settings.VIDEO_RESOLUTIONS
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_auto_20200221_1433"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="resolutions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(max_length=10),
                blank=True,
                help_text="List of available sizes for this video",
                null=True,
                size=None,
                verbose_name="video sizes",
            ),
        ),
        migrations.RunPython(initialize_video_resolutions),
    ]
