# Generated by Django 3.1.3 on 2020-11-16 16:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_auto_20200609_0820"),
    ]

    operations = [
        migrations.AddField(
            model_name="timedtexttrack",
            name="extension",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="timed text track extension",
                max_length=10,
                null=True,
                verbose_name="extension",
            ),
        ),
    ]
