# Generated by Django 3.1.7 on 2021-03-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_auto_20201210_1353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="lti_id",
            field=models.CharField(
                blank=True,
                help_text="ID for synchronization with an external LTI tool",
                max_length=255,
                null=True,
                verbose_name="lti id",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="lti_id",
            field=models.CharField(
                blank=True,
                help_text="ID for synchronization with an external LTI tool",
                max_length=255,
                null=True,
                verbose_name="lti id",
            ),
        ),
    ]
