# Generated by Django 3.2.9 on 2021-11-25 11:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_auto_20210924_0707"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="starting_at",
            field=models.DateTimeField(
                blank=True,
                help_text="date and time at which the live is scheduled",
                null=True,
                verbose_name="starting at",
            ),
        ),
    ]
