# Generated by Django 3.2.9 on 2021-12-15 12:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def migrate_is_registered(apps, schema_editor):
    """Update existing records to set is_registered to True."""
    Liveregistrations = apps.get_model("core", "Liveregistration")
    Liveregistrations.objects.filter(is_registered=False).update(is_registered=True)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_auto_20211213_1457"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveregistration",
            name="is_registered",
            field=models.BooleanField(
                default=False,
                help_text="Is the user registered?",
                verbose_name="is the user registered",
            ),
        ),
        migrations.AddField(
            model_name="liveregistration",
            name="live_attendance",
            field=models.JSONField(
                blank=True,
                help_text="Live online presence",
                null=True,
                verbose_name="Live attendance",
            ),
        ),
        migrations.AddField(
            model_name="liveregistration",
            name="username",
            field=models.CharField(
                blank=True, max_length=155, null=True, verbose_name="Username"
            ),
        ),
        migrations.AddConstraint(
            model_name="liveregistration",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("email__isnull", True), ("is_registered", False)),
                    ("email__isnull", False),
                    _connector="OR",
                ),
                name="liveregistration_email_is_registered",
            ),
        ),
        migrations.RunPython(migrate_is_registered),
    ]
