# Generated by Django 3.2.10 on 2021-12-20 16:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_auto_20211220_1203"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="active_shared_live_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_video",
                to="core.sharedlivemedia",
                verbose_name="Video",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="active_shared_live_media_page",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Current displayed page of the active shared live media",
                null=True,
            ),
        ),
    ]
