# Generated by Django 3.2.11 on 2022-01-05 16:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_auto_20211220_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="allow_recording",
            field=models.BooleanField(
                default=True,
                help_text="Allow video recording?",
                verbose_name="allow video recording",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="estimated_duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Estimated duration of the video in seconds.",
                null=True,
                verbose_name="estimated duration",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="has_chat",
            field=models.BooleanField(
                default=True,
                help_text="Enable video chat?",
                verbose_name="enable video chat",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="has_live_media",
            field=models.BooleanField(
                default=True,
                help_text="Enable video live media?",
                verbose_name="enable video live media",
            ),
        ),
    ]
