# Generated by Django 3.2.11 on 2022-01-19 09:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_auto_20220105_1600"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveregistration",
            name="reminders",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                help_text="List of reminders already sent",
                null=True,
                size=None,
                verbose_name="List of reminders sent",
            ),
        ),
        migrations.AlterField(
            model_name="liveregistration",
            name="is_registered",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Is the user registered?",
                verbose_name="is the user registered",
            ),
        ),
        migrations.AlterField(
            model_name="liveregistration",
            name="should_send_reminders",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="whether user reminders are enabled for this live",
                verbose_name="should send reminders",
            ),
        ),
    ]
