# Generated by Django 4.0.2 on 2022-03-03 15:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_auto_20220216_1713"),
    ]

    operations = [
        migrations.RenameModel("LiveRegistration", "LiveSession"),
        migrations.AlterModelOptions(
            name="livesession",
            options={"verbose_name": "live session"},
        ),
        migrations.RemoveConstraint(
            model_name="livesession",
            name="liveregistration_unique_email_video_with_consumer_site_none",
        ),
        migrations.RemoveConstraint(
            model_name="livesession",
            name="liveregistration_unique_video_lti_idx",
        ),
        migrations.RemoveConstraint(
            model_name="livesession",
            name="liveregistration_email_is_registered",
        ),
        migrations.RemoveConstraint(
            model_name="livesession",
            name="liveregistration_lti_or_public",
        ),
        migrations.RemoveConstraint(
            model_name="livesession",
            name="liveregistration_unique_video_display_name",
        ),
        migrations.RemoveConstraint(
            model_name="livesession",
            name="liveregistration_unique_video_anonymous_id",
        ),
        migrations.AlterField(
            model_name="livesession",
            name="consumer_site",
            field=models.ForeignKey(
                blank=True,
                help_text="Only present for lti users.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livesessions",
                to="core.consumersite",
                verbose_name="LTI consumer site",
            ),
        ),
        migrations.AlterField(
            model_name="livesession",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livesessions",
                to="core.video",
                verbose_name="Video",
            ),
        ),
        migrations.AddConstraint(
            model_name="livesession",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("consumer_site__isnull", False),
                        ("lti_id__isnull", False),
                        ("lti_user_id__isnull", False),
                    ),
                    models.Q(
                        ("anonymous_id__isnull", False),
                        ("consumer_site__isnull", True),
                        ("lti_id__isnull", True),
                        ("lti_user_id__isnull", True),
                        ("username__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="livesession_lti_or_public",
            ),
        ),
        migrations.AddConstraint(
            model_name="livesession",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("email__isnull", True), ("is_registered", False)),
                    ("email__isnull", False),
                    _connector="OR",
                ),
                name="livesession_email_is_registered",
            ),
        ),
        migrations.AddConstraint(
            model_name="livesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("consumer_site", None), ("deleted", None)),
                fields=("email", "video"),
                name="livesession_unique_email_video_with_consumer_site_none",
            ),
        ),
        migrations.AddConstraint(
            model_name="livesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("lti_user_id", "lti_id", "consumer_site", "video"),
                name="livesession_unique_video_lti_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="livesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("display_name", "video"),
                name="livesession_unique_video_display_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="livesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("anonymous_id", "video"),
                name="livesession_unique_video_anonymous_id",
            ),
        ),
        migrations.AlterModelTable(
            name="livesession",
            table="live_session",
        ),
    ]
