# Generated by Django 4.0.2 on 2022-02-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_auto_20220303_1536"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="participants_asking_to_join",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Current list of users asking to join the live.",
                verbose_name="asking Live participants",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="participants_in_discussion",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Current participants list for the live.",
                verbose_name="live participants",
            ),
        ),
    ]
