# Generated by Django 4.0.3 on 2022-03-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_video_participantsaskingtojoin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livesession",
            name="channel_name",
            field=models.CharField(
                blank=True,
                help_text="Websocket channel_name",
                max_length=255,
                null=True,
            ),
        )
    ]
