# Generated by Django 4.0.2 on 2022-03-02 10:02

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_livesession_channel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="recording_slices",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Recording slices of the video.",
                verbose_name="recording slices",
            ),
        ),
    ]
