# Generated by Django 4.0.3 on 2022-03-31 13:55

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_add_video_recording_slices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="title of the file",
                max_length=255,
                null=True,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="title of the file",
                max_length=255,
                null=True,
                verbose_name="title",
            ),
        ),
    ]
