# Generated by Django 4.0.3 on 2022-04-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_nullable_base_file_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="livesession",
            name="registered_at",
            field=models.DateTimeField(
                blank=True,
                help_text="date and time at which the user registered",
                null=True,
                verbose_name="registered at",
            ),
        ),
    ]
