# Generated by Django 4.0.3 on 2022-04-07 15:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_nullable_base_file_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="must_notify",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                default=list,
                help_text="List of new notification to send",
                size=None,
                verbose_name="List of new notification to send",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="starting_at_updated_on",
            field=models.DateTimeField(
                blank=True,
                help_text="date and time at which a starting_at was last updated",
                null=True,
                verbose_name="starting updated on",
            ),
        ),
    ]
