# Generated by Django 4.0.3 on 2022-04-19 15:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_remove_video_video_unique_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="estimated_duration",
        ),
        migrations.AddField(
            model_name="video",
            name="estimated_duration",
            field=models.DurationField(
                blank=True,
                help_text="Estimated duration of the video.",
                null=True,
                verbose_name="estimated duration",
            ),
        ),
    ]
