# Generated by Django 4.0.3 on 2022-04-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_remove_video_estimated_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livesession",
            name="language",
            field=models.CharField(
                choices=[("en", "english"), ("fr", "french")],
                default="en",
                help_text="language of this livesession",
                max_length=10,
                verbose_name="language",
            ),
        )
    ]
