# Generated by Django 4.0.5 on 2022-06-07 13:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_add_video_join_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thumbnail",
            name="video",
            field=models.ForeignKey(
                help_text="video for which this thumbnail is",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thumbnail",
                to="core.video",
                verbose_name="video",
            ),
        ),
        migrations.AddConstraint(
            model_name="thumbnail",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("video",),
                name="thumbnail_video_unique_idx",
            ),
        ),
    ]
