# Generated by Django 4.0.4 on 2022-05-27 18:32

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_add_video_join_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="join_mode",
            field=models.CharField(
                choices=[("open", "open"), ("closed", "closed"), ("forced", "forced")],
                default="open",
                help_text="Join discussion mode.",
                max_length=20,
                verbose_name="Join discussion mode",
            ),
        ),
    ]
