# Generated by Django 4.0.6 on 2022-07-26 09:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_migrate_livesession_liveattendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                help_text="video tags",
                default=list,
                size=None,
            ),
        ),
    ]
