# Generated by Django 4.0.7 on 2022-09-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_video_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiotrack",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="audiotrack",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                    ("deleted", "deleted"),
                    ("scanning", "scanning"),
                    ("infected", "infected"),
                    ("copying", "copying"),
                ],
                default="pending",
                help_text="state of the upload in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
        migrations.AlterField(
            model_name="consumersite",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="consumersiteaccess",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="consumersiteorganization",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="consumersiteportability",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                    ("deleted", "deleted"),
                    ("scanning", "scanning"),
                    ("infected", "infected"),
                    ("copying", "copying"),
                ],
                default="pending",
                help_text="state of the upload in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
        migrations.AlterField(
            model_name="livepairing",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="livesession",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="ltipassport",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="organizationaccess",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="playlistaccess",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="playlistportability",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="sharedlivemedia",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="sharedlivemedia",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                    ("deleted", "deleted"),
                    ("scanning", "scanning"),
                    ("infected", "infected"),
                    ("copying", "copying"),
                ],
                default="pending",
                help_text="state of the upload in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
        migrations.AlterField(
            model_name="signtrack",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="signtrack",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                    ("deleted", "deleted"),
                    ("scanning", "scanning"),
                    ("infected", "infected"),
                    ("copying", "copying"),
                ],
                default="pending",
                help_text="state of the upload in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                    ("deleted", "deleted"),
                    ("scanning", "scanning"),
                    ("infected", "infected"),
                    ("copying", "copying"),
                ],
                default="pending",
                help_text="state of the upload in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
        migrations.AlterField(
            model_name="timedtexttrack",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="timedtexttrack",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                    ("deleted", "deleted"),
                    ("scanning", "scanning"),
                    ("infected", "infected"),
                    ("copying", "copying"),
                ],
                default="pending",
                help_text="state of the upload in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                    ("deleted", "deleted"),
                    ("scanning", "scanning"),
                    ("infected", "infected"),
                    ("copying", "copying"),
                ],
                default="pending",
                help_text="state of the upload in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
    ]
