# Generated by Django 4.0.7 on 2022-09-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_alter_audiotrack_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiotrack",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("initialized", "initialized"),
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                    ("deleted", "deleted"),
                    ("scanning", "scanning"),
                    ("infected", "infected"),
                    ("copying", "copying"),
                ],
                default="pending",
                help_text="state of the upload in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("initialized", "initialized"),
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                    ("deleted", "deleted"),
                    ("scanning", "scanning"),
                    ("infected", "infected"),
                    ("copying", "copying"),
                ],
                default="pending",
                help_text="state of the upload in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
        migrations.AlterField(
            model_name="sharedlivemedia",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("initialized", "initialized"),
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                    ("deleted", "deleted"),
                    ("scanning", "scanning"),
                    ("infected", "infected"),
                    ("copying", "copying"),
                ],
                default="pending",
                help_text="state of the upload in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
        migrations.AlterField(
            model_name="signtrack",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("initialized", "initialized"),
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                    ("deleted", "deleted"),
                    ("scanning", "scanning"),
                    ("infected", "infected"),
                    ("copying", "copying"),
                ],
                default="pending",
                help_text="state of the upload in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("initialized", "initialized"),
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                    ("deleted", "deleted"),
                    ("scanning", "scanning"),
                    ("infected", "infected"),
                    ("copying", "copying"),
                ],
                default="pending",
                help_text="state of the upload in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
        migrations.AlterField(
            model_name="timedtexttrack",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("initialized", "initialized"),
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                    ("deleted", "deleted"),
                    ("scanning", "scanning"),
                    ("infected", "infected"),
                    ("copying", "copying"),
                ],
                default="pending",
                help_text="state of the upload in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="upload_state",
            field=models.CharField(
                choices=[
                    ("initialized", "initialized"),
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("error", "error"),
                    ("ready", "ready"),
                    ("deleted", "deleted"),
                    ("scanning", "scanning"),
                    ("infected", "infected"),
                    ("copying", "copying"),
                ],
                default="pending",
                help_text="state of the upload in AWS.",
                max_length=20,
                verbose_name="upload state",
            ),
        ),
    ]
