# Generated by Django 4.0.5 on 2022-10-04 11:41

import uuid

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_noop_alter_audiotrack_upload_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LtiUserAssociation",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "lti_user_id",
                    models.CharField(
                        db_index=True,
                        help_text="LMS user ID",
                        max_length=255,
                        verbose_name="LTI user ID",
                    ),
                ),
                (
                    "consumer_site",
                    models.ForeignKey(
                        help_text="consumer site related to this user association",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lti_user_associations",
                        to="core.consumersite",
                        verbose_name="consumer site",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="user related to this user association",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lti_user_associations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "LTI user association",
                "verbose_name_plural": "LTI user associations",
                "db_table": "lti_user_association",
            },
        ),
        migrations.AddConstraint(
            model_name="ltiuserassociation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("lti_user_id", "consumer_site"),
                name="lti_user_association_unique_per_consumer_site_idx",
            ),
        ),
    ]
