# Generated by Django 4.0.8 on 2022-11-22 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_add_portabilityrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="consumer_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to="core.consumersite",
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="lti_id",
            field=models.CharField(
                blank=True,
                help_text="ID for synchronization with an external LTI tool",
                max_length=255,
                null=True,
                verbose_name="lti id",
            ),
        ),
        migrations.AddConstraint(
            model_name="playlist",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            ("consumer_site__isnull", False), ("lti_id__isnull", False)
                        ),
                        models.Q(
                            ("consumer_site__isnull", True),
                            ("lti_id__isnull", True),
                            ("organization__isnull", False),
                        ),
                        _connector="OR",
                    )
                ),
                name="consumer_site_or_organization_check_idx",
            ),
        ),
    ]
