# Generated by Django 4.0.10 on 2023-02-28 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_alter_playlist_consumer_site_alter_playlist_lti_id_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="livesession",
            name="livesession_lti_or_public",
        ),
        migrations.RemoveConstraint(
            model_name="livesession",
            name="livesession_unique_email_video_with_consumer_site_none",
        ),
        migrations.AddField(
            model_name="livesession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livesessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddConstraint(
            model_name="livesession",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("consumer_site__isnull", False),
                        ("lti_id__isnull", False),
                        ("lti_user_id__isnull", False),
                        ("user__isnull", True),
                    ),
                    models.Q(
                        ("anonymous_id__isnull", False),
                        ("consumer_site__isnull", True),
                        ("lti_id__isnull", True),
                        ("lti_user_id__isnull", True),
                        ("user__isnull", True),
                        ("username__isnull", True),
                    ),
                    models.Q(
                        ("anonymous_id__isnull", True),
                        ("consumer_site__isnull", True),
                        ("lti_id__isnull", True),
                        ("lti_user_id__isnull", True),
                        ("user__isnull", False),
                        ("username__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="livesession_lti_or_public_or_standalone",
            ),
        ),
        migrations.AddConstraint(
            model_name="livesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("consumer_site__isnull", True),
                    ("deleted", None),
                    ("user__isnull", True),
                ),
                fields=("email", "video"),
                name="livesession_unique_email_video_with_consumer_site_user_none",
            ),
        ),
        migrations.AddConstraint(
            model_name="livesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("user", "video"),
                name="livesession_unique_video_user",
            ),
        ),
    ]
