# Generated by Django 4.0.10 on 2023-03-29 11:17

from django.db import migrations, models

import marsha.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_remove_livesession_livesession_lti_or_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumersite",
            name="inactive_resources",
            field=marsha.core.fields.InvertedArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("video", "video"),
                        ("webinar", "webinar"),
                        ("document", "document"),
                        ("classroom", "classroom"),
                        ("markdown", "markdown"),
                        ("deposit", "deposit file"),
                    ],
                    max_length=100,
                    null=True,
                ),
                blank=True,
                default=list,
                help_text="list of resources that are active for this consumer site.",
                size=None,
                verbose_name="active resources",
            ),
        ),
    ]
