# Generated by Django 4.1.7 on 2023-04-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_consumersite_inactive_resources"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="video",
            name="live_type_check",
        ),
        migrations.AddConstraint(
            model_name="video",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(
                            ("live_state__isnull", True), ("live_type__isnull", True)
                        ),
                        models.Q(
                            ("live_state__isnull", False), ("live_type__isnull", False)
                        ),
                        _connector="OR",
                    )
                ),
                name="live_type_check",
            ),
        ),
    ]
