# Generated by Django 4.1.9 on 2023-05-10 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_remove_video_live_type_check_video_live_type_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="active_shared_live_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_video",
                to="core.sharedlivemedia",
                verbose_name="Video",
            ),
        ),
    ]
