# Generated by Django 4.1.9 on 2023-05-30 11:21

import uuid

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_alter_video_active_shared_live_media"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaylistVideo",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_videos",
                        to="core.playlist",
                        verbose_name="playlist",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_videos",
                        to="core.video",
                        verbose_name="video",
                    ),
                ),
            ],
            options={
                "db_table": "playlist_video",
                "unique_together": {("playlist", "video")},
            },
        ),
        migrations.CreateModel(
            name="PlaylistDocument",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_documents",
                        to="core.document",
                        verbose_name="document",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        help_text="playlist to which this document belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_documents",
                        to="core.playlist",
                        verbose_name="playlist",
                    ),
                ),
            ],
            options={
                "db_table": "playlist_document",
                "unique_together": {("playlist", "document")},
            },
        ),
        migrations.AddField(
            model_name="document",
            name="playlists",
            field=models.ManyToManyField(
                help_text="playlists to which this document belongs",
                related_name="documents_many_to_many",
                through="core.PlaylistDocument",
                to="core.playlist",
                verbose_name="playlists",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="playlists",
            field=models.ManyToManyField(
                help_text="The playlists this video belongs to.",
                related_name="videos_many_to_many",
                through="core.PlaylistVideo",
                to="core.playlist",
                verbose_name="playlists",
            ),
        ),
    ]
