# Generated by Django 4.1.9 on 2023-05-30 11:22

from django.db import migrations


def migrate_playlist(apps, schema_editor):
    """Migrate playlist to playlistvideo and playlistdocument."""
    try:
        playlists = apps.get_model("core", "Playlist")
        playlistvideos = apps.get_model("core", "PlaylistVideo")
        playlistdocuments = apps.get_model("core", "PlaylistDocument")
    except LookupError:
        return

    for playlist in playlists.objects.all():
        for video in playlist.videos.all():
            playlistvideos.objects.create(playlist=playlist, video=video)

        for document in playlist.documents.all():
            playlistdocuments.objects.create(playlist=playlist, document=document)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_playlistvideo_playlistdocument_document_playlists_and_more"),
    ]

    operations = [migrations.RunPython(migrate_playlist)]
