# Generated by Django 4.1.9 on 2023-06-05 08:49

from django.db import migrations, models

import marsha.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_siteconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumersite",
            name="inactive_features",
            field=marsha.core.fields.InvertedArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[("vod_convert", "VOD conversion")],
                    max_length=100,
                    null=True,
                ),
                blank=True,
                default=list,
                help_text="list of features that are active for this consumer site.",
                size=None,
                verbose_name="active features",
            ),
        ),
    ]
