# Generated by Django 4.1.9 on 2023-06-05 12:39

from django.db import migrations, models

import marsha.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_consumersite_inactive_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="inactive_features",
            field=marsha.core.fields.InvertedArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[("vod_convert", "VOD conversion")],
                    max_length=100,
                    null=True,
                ),
                blank=True,
                default=list,
                help_text="list of features that are active for this organization.",
                size=None,
                verbose_name="active features",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="inactive_resources",
            field=marsha.core.fields.InvertedArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("video", "video"),
                        ("webinar", "webinar"),
                        ("document", "document"),
                        ("classroom", "classroom"),
                        ("markdown", "markdown"),
                        ("deposit", "deposit file"),
                    ],
                    max_length=100,
                    null=True,
                ),
                blank=True,
                default=list,
                help_text="list of resources that are active for this organization.",
                size=None,
                verbose_name="active resources",
            ),
        ),
    ]
