# Generated by Django 4.1.9 on 2023-07-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_organization_inactive_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="retention_duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duration in days after which the related objects should be deleted",
                null=True,
                verbose_name="retention duration in day",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="retention_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the video and its related resources should be deleted",
                null=True,
                verbose_name="retention date",
            ),
        ),
    ]
