# Generated by Django 4.2.3 on 2023-07-13 06:52

from django.db import migrations, models

import marsha.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_siteconfig_footer_copyright_siteconfig_login_html_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="inactive_features",
            field=marsha.core.fields.InvertedArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[("vod_convert", "VOD conversion")],
                    max_length=100,
                    null=True,
                ),
                blank=True,
                default=list,
                help_text="list of features that are active for this site.",
                size=None,
                verbose_name="active features",
            ),
        ),
    ]
