# Generated by Django 4.2.3 on 2023-08-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0068_siteconfig_inactive_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="saml_entity_id",
            field=models.CharField(
                blank=True,
                help_text="should be a URL that includes a domain name you own",
                max_length=255,
                null=True,
                verbose_name="saml entity id",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="saml_organization_info",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Organization info for your app",
                verbose_name="SAML organization info",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="saml_support_contact",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Support contact responsible for your app",
                verbose_name="SAML support contact",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="saml_technical_contact",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Technical contact responsible for your app",
                verbose_name="SAML technical contact",
            ),
        ),
    ]
