# Generated by Django 4.2.4 on 2023-09-08 14:13

from django.db import migrations


def migrate_is_claimable(apps, schema_editor):
    """Update existing playlists to set is_claimable to True."""
    Playlists = apps.get_model("core", "Playlist")
    Playlists.objects.filter(is_claimable=None).update(is_claimable=True)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0070_playlist_is_claimable_alter_video_license"),
    ]

    operations = [migrations.RunPython(migrate_is_claimable)]
