# Generated by Django 4.2.5 on 2023-09-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0070_playlist_is_claimable_alter_video_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="last_lti_url",
            field=models.URLField(
                blank=True,
                help_text="Last LTI URL which was used to launch this video",
                null=True,
                verbose_name="last LTI URL",
            ),
        ),
    ]
