# Generated by Django 4.2.5 on 2023-10-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0071_video_last_lti_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="homepage_banner_text",
            field=models.TextField(
                blank=True,
                help_text="Homepage banner text",
                null=True,
                verbose_name="Homepage banner text",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="homepage_banner_title",
            field=models.CharField(
                blank=True,
                help_text="Homepage banner title",
                max_length=255,
                null=True,
                verbose_name="Homepage banner title",
            ),
        ),
    ]
