# Generated by Django 4.2.5 on 2023-10-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_siteconfig_homepage_banner_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="is_logo_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Is the logo enabled ?",
                null=True,
                verbose_name="logo enabled",
            ),
        ),
    ]
