# Generated by Django 4.2.5 on 2023-10-17 09:56

from django.db import migrations, models
from django.db.models import Q


def migrate_aws_transcode_pipeline(apps, schema_editor):
    """Update existing transcoded video to aws pipeline."""
    Video = apps.get_model("core", "Video")
    Video.objects.filter(Q(live_state__isnull=True) | Q(live_state="ended")).update(
        transcode_pipeline="AWS"
    )
    Video.objects.filter(uploaded_on__isnull=False).update(transcode_pipeline="AWS")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_siteconfig_is_logo_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="transcode_pipeline",
            field=models.CharField(
                blank=True,
                choices=[("AWS", "AWS")],
                help_text="Transcode pipeline for this video",
                max_length=255,
                null=True,
                verbose_name="transcode pipeline",
            ),
        ),
        migrations.RunPython(migrate_aws_transcode_pipeline, migrations.RunPython.noop),
    ]
