# Generated by Django 4.2.4 on 2023-11-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_video_transcode_pipeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="The meta description of the site",
                null=True,
                verbose_name="meta description",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="meta_title",
            field=models.TextField(
                blank=True,
                help_text="The meta title of the site",
                null=True,
                verbose_name="meta title",
            ),
        ),
    ]
