# Generated by Django 4.2.7 on 2023-11-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_siteconfig_meta_description_siteconfig_meta_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="transcode_pipeline",
            field=models.CharField(
                blank=True,
                choices=[("AWS", "AWS"), ("peertube", "Peertube")],
                help_text="Transcode pipeline for this video",
                max_length=255,
                null=True,
                verbose_name="transcode pipeline",
            ),
        ),
    ]
