# Generated by Django 4.2.16 on 2024-11-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_alter_playlist_lti_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="upload_error_reason",
            field=models.CharField(
                blank=True,
                choices=[("max_resolution_excedeed", "max_resolution_excedeed")],
                help_text="Reason why an upload is in error state.",
                max_length=50,
                null=True,
                verbose_name="upload error reason",
            ),
        ),
    ]
