# Generated by Django 4.2.16 on 2024-11-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_video_upload_error_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="duration",
            field=models.FloatField(
                blank=True, help_text="Duration of the video in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="size",
            field=models.IntegerField(
                blank=True, help_text="Size of the video in bytes", null=True
            ),
        ),
    ]
