# Generated by Django 5.0.9 on 2025-06-19 10:04

from django.db import migrations, models


def set_storage_location_to_aws(apps, schema_editor):
    """Update the storage_location field for existing documents."""
    Document = apps.get_model("core", "Document")
    Document.objects.all().update(storage_location="AWS_S3")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_alter_video_upload_error_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="filename",
            field=models.CharField(
                blank=True,
                help_text="filename of the document",
                max_length=255,
                null=True,
                verbose_name="filename",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="storage_location",
            field=models.CharField(
                choices=[("AWS", "AWS"), ("SCW", "SCW")],
                default="SCW",
                help_text="Location used to store the document",
                max_length=255,
                verbose_name="storage location",
            ),
        ),
        migrations.RunPython(set_storage_location_to_aws, migrations.RunPython.noop),
    ]
