# Generated by Django 5.0.9 on 2025-06-11 17:34

from django.db import migrations

from marsha.core.defaults import AWS_S3


def fix_storage_location_to_aws(apps, schema_editor):
    """Update the storage_location field for existing documents."""
    Document = apps.get_model("core", "Document")
    Document.objects.filter(storage_location="AWS_S3").update(storage_location=AWS_S3)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_document_filename_document_storage_location_and_more"),
    ]

    operations = [
        migrations.RunPython(fix_storage_location_to_aws, migrations.RunPython.noop),
    ]
